
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.extrememonsters.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.OnlyIn;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

import net.mcreator.extrememonsters.procedures.WitheredDarkMatterLauncherTextureChangeProcedure;
import net.mcreator.extrememonsters.item.inventory.PosTeleporterInventoryCapability;
import net.mcreator.extrememonsters.item.ZioWrenchItem;
import net.mcreator.extrememonsters.item.WitheredDarkMatterLauncherItem;
import net.mcreator.extrememonsters.item.WitherMatterSwordItem;
import net.mcreator.extrememonsters.item.WitherMatterItem;
import net.mcreator.extrememonsters.item.WitherMatterIngotItem;
import net.mcreator.extrememonsters.item.WitherMatterHammerItem;
import net.mcreator.extrememonsters.item.WitherMatterFuelItem;
import net.mcreator.extrememonsters.item.WitherMatterCrystalMatrixIngotItem;
import net.mcreator.extrememonsters.item.WitherMatterBandAidItem;
import net.mcreator.extrememonsters.item.WitherMatterArmorItem;
import net.mcreator.extrememonsters.item.WitherMatterAppleItem;
import net.mcreator.extrememonsters.item.WitherInTheBottleItem;
import net.mcreator.extrememonsters.item.VaporEmitterItem;
import net.mcreator.extrememonsters.item.UsableStarsSoulItem;
import net.mcreator.extrememonsters.item.UpgradedArrowRemoverItem;
import net.mcreator.extrememonsters.item.UltimateSoulItem;
import net.mcreator.extrememonsters.item.UltimateIngotItem;
import net.mcreator.extrememonsters.item.UltimateCoreItem;
import net.mcreator.extrememonsters.item.UltimateCatalystItem;
import net.mcreator.extrememonsters.item.TungstenIngotItem;
import net.mcreator.extrememonsters.item.TungstenCrystalMatrixIngotItem;
import net.mcreator.extrememonsters.item.TungstenBatItem;
import net.mcreator.extrememonsters.item.TrackersVoidItem;
import net.mcreator.extrememonsters.item.TrackersSoulItem;
import net.mcreator.extrememonsters.item.TrackersAbyssItem;
import net.mcreator.extrememonsters.item.TrackerSpawnDetectorItem;
import net.mcreator.extrememonsters.item.TrackerInTheBottleItem;
import net.mcreator.extrememonsters.item.TrackerCoreItem;
import net.mcreator.extrememonsters.item.TrackerAvoiderItem;
import net.mcreator.extrememonsters.item.TotemOfBlackholeItem;
import net.mcreator.extrememonsters.item.SuperchargedDarkMatterItem;
import net.mcreator.extrememonsters.item.SuperTrackerPagerItem;
import net.mcreator.extrememonsters.item.SuperMatterCatalystItem;
import net.mcreator.extrememonsters.item.SuperLavaItem;
import net.mcreator.extrememonsters.item.SuperDamageProtectorItem;
import net.mcreator.extrememonsters.item.StellarCatalystItem;
import net.mcreator.extrememonsters.item.StasisRailGunStickItem;
import net.mcreator.extrememonsters.item.StasisRailGunItem;
import net.mcreator.extrememonsters.item.StasisLaserEmitterItem;
import net.mcreator.extrememonsters.item.StartExtremeItem;
import net.mcreator.extrememonsters.item.StarsSoulItem;
import net.mcreator.extrememonsters.item.SpeedUpgrade2Item;
import net.mcreator.extrememonsters.item.SpeedUpgrade1Item;
import net.mcreator.extrememonsters.item.SoulEssenceItem;
import net.mcreator.extrememonsters.item.SoulCollectorItem;
import net.mcreator.extrememonsters.item.SmeltingUpgradeItem;
import net.mcreator.extrememonsters.item.SmeltingStickItem;
import net.mcreator.extrememonsters.item.SingularityItem;
import net.mcreator.extrememonsters.item.SchemaTungstenItem;
import net.mcreator.extrememonsters.item.SchemaStoneItem;
import net.mcreator.extrememonsters.item.SchemaRedstoneItem;
import net.mcreator.extrememonsters.item.SchemaQuartzItem;
import net.mcreator.extrememonsters.item.SchemaNetheriteItem;
import net.mcreator.extrememonsters.item.SchemaNetherStarItem;
import net.mcreator.extrememonsters.item.SchemaIronItem;
import net.mcreator.extrememonsters.item.SchemaGoldItem;
import net.mcreator.extrememonsters.item.SchemaDiamondItem;
import net.mcreator.extrememonsters.item.SchemaCopperItem;
import net.mcreator.extrememonsters.item.SchemaCoalItem;
import net.mcreator.extrememonsters.item.SchemaAmethystItem;
import net.mcreator.extrememonsters.item.RingOfFlightItem;
import net.mcreator.extrememonsters.item.RawTungstenItem;
import net.mcreator.extrememonsters.item.QuasarItem;
import net.mcreator.extrememonsters.item.QuantumEntanglerItem;
import net.mcreator.extrememonsters.item.PosTeleporterItem;
import net.mcreator.extrememonsters.item.PerfectMatterSwordItem;
import net.mcreator.extrememonsters.item.PerfectMatterItem;
import net.mcreator.extrememonsters.item.PerfectMatterHammerItem;
import net.mcreator.extrememonsters.item.PerfectMatterFragmentItem;
import net.mcreator.extrememonsters.item.PerfectMatterArmorItem;
import net.mcreator.extrememonsters.item.PerfectDarkMatterBarragerItem;
import net.mcreator.extrememonsters.item.PerfectAbyssItem;
import net.mcreator.extrememonsters.item.OmegaWrenchItem;
import net.mcreator.extrememonsters.item.NormalArrowItem;
import net.mcreator.extrememonsters.item.NomalArrowBarragerItem;
import net.mcreator.extrememonsters.item.NetherPassItem;
import net.mcreator.extrememonsters.item.MolecularSolventItem;
import net.mcreator.extrememonsters.item.MolecularAlloyIngotItem;
import net.mcreator.extrememonsters.item.MobImmobilizerItem;
import net.mcreator.extrememonsters.item.MobDisruptorItem;
import net.mcreator.extrememonsters.item.MixedHyperIngotItem;
import net.mcreator.extrememonsters.item.MixedHyperEssenceItem;
import net.mcreator.extrememonsters.item.MirrorOfDespairItem;
import net.mcreator.extrememonsters.item.MicroverseSchemaItem;
import net.mcreator.extrememonsters.item.MatterCatalystShardItem;
import net.mcreator.extrememonsters.item.MatterCatalystItem;
import net.mcreator.extrememonsters.item.MatterCatalystIngotItem;
import net.mcreator.extrememonsters.item.MVSEraChangerItem;
import net.mcreator.extrememonsters.item.InfiniteWaterAmuletItem;
import net.mcreator.extrememonsters.item.InfiniteLavaAmuletItem;
import net.mcreator.extrememonsters.item.InfernoRailGunStickItem;
import net.mcreator.extrememonsters.item.InfernoRailGunItem;
import net.mcreator.extrememonsters.item.InfernoMatterSwordItem;
import net.mcreator.extrememonsters.item.InfernoMatterShardItem;
import net.mcreator.extrememonsters.item.InfernoMatterItem;
import net.mcreator.extrememonsters.item.InfernoMatterIngotItem;
import net.mcreator.extrememonsters.item.InfernoMatterHammerItem;
import net.mcreator.extrememonsters.item.InfernoMatterFuelItem;
import net.mcreator.extrememonsters.item.InfernoMatterExpBottleItem;
import net.mcreator.extrememonsters.item.InfernoMatterCrystalMatrixIngotItem;
import net.mcreator.extrememonsters.item.InfernoMatterBombItem;
import net.mcreator.extrememonsters.item.InfernoMatterBandAidItem;
import net.mcreator.extrememonsters.item.InfernoMatterArmorItem;
import net.mcreator.extrememonsters.item.InfernoMatterAppleItem;
import net.mcreator.extrememonsters.item.HyperZombifiedPiglinsSoulItem;
import net.mcreator.extrememonsters.item.HyperZombiesSoulItem;
import net.mcreator.extrememonsters.item.HyperWitheredBoneItem;
import net.mcreator.extrememonsters.item.HyperWitherSkeletonsSoulItem;
import net.mcreator.extrememonsters.item.HyperWitherIngotItem;
import net.mcreator.extrememonsters.item.HyperWitherInTheBottleItem;
import net.mcreator.extrememonsters.item.HyperTrackerPagerItem;
import net.mcreator.extrememonsters.item.HyperTrackerInTheBottleItem;
import net.mcreator.extrememonsters.item.HyperTotemOfUndyingItem;
import net.mcreator.extrememonsters.item.HyperStoneDestroyerItem;
import net.mcreator.extrememonsters.item.HyperStaffItem;
import net.mcreator.extrememonsters.item.HyperSpidersSoulItem;
import net.mcreator.extrememonsters.item.HyperSpiderEyeItem;
import net.mcreator.extrememonsters.item.HyperSkeletonsSoulItem;
import net.mcreator.extrememonsters.item.HyperRottenFleshItem;
import net.mcreator.extrememonsters.item.HyperNetherStarItem;
import net.mcreator.extrememonsters.item.HyperMobDesignatorItem;
import net.mcreator.extrememonsters.item.HyperMagmaCubesSoulItem;
import net.mcreator.extrememonsters.item.HyperMagmaCreamItem;
import net.mcreator.extrememonsters.item.HyperItemMagnetItem;
import net.mcreator.extrememonsters.item.HyperIngot3Item;
import net.mcreator.extrememonsters.item.HyperIngot2Item;
import net.mcreator.extrememonsters.item.HyperIngot1Item;
import net.mcreator.extrememonsters.item.HyperGunpowderItem;
import net.mcreator.extrememonsters.item.HyperGoldenAxeItem;
import net.mcreator.extrememonsters.item.HyperGoldPickaxeItem;
import net.mcreator.extrememonsters.item.HyperGoldNuggetItem;
import net.mcreator.extrememonsters.item.HyperGoldIngotItem;
import net.mcreator.extrememonsters.item.HyperEssence4Item;
import net.mcreator.extrememonsters.item.HyperEssence3Item;
import net.mcreator.extrememonsters.item.HyperEnssence2Item;
import net.mcreator.extrememonsters.item.HyperEnssence1Item;
import net.mcreator.extrememonsters.item.HyperEndermansSoulItem;
import net.mcreator.extrememonsters.item.HyperEnderWitherInTheBottleItem;
import net.mcreator.extrememonsters.item.HyperEnderPearlItem;
import net.mcreator.extrememonsters.item.HyperEnderDragonInTheBottleItem;
import net.mcreator.extrememonsters.item.HyperDragonSkinItem;
import net.mcreator.extrememonsters.item.HyperDragonIngotItem;
import net.mcreator.extrememonsters.item.HyperCreepersSoulItem;
import net.mcreator.extrememonsters.item.HyperBoneItem;
import net.mcreator.extrememonsters.item.HyperBlazesSoulItem;
import net.mcreator.extrememonsters.item.HyperBlazeRodItem;
import net.mcreator.extrememonsters.item.FierySoulCollectorItem;
import net.mcreator.extrememonsters.item.FictionalPlanetModelItem;
import net.mcreator.extrememonsters.item.ExplosiveEmitterItem;
import net.mcreator.extrememonsters.item.EvasionAmuletItem;
import net.mcreator.extrememonsters.item.EternalDarkMatterAppleItem;
import net.mcreator.extrememonsters.item.EternalBlackHoleMatterAppleItem;
import net.mcreator.extrememonsters.item.EnderDragonInTheBottleItem;
import net.mcreator.extrememonsters.item.EndPassItem;
import net.mcreator.extrememonsters.item.EmptyItemSlotItem;
import net.mcreator.extrememonsters.item.DuplicatedSoulItem;
import net.mcreator.extrememonsters.item.DuplicatedNetherStarItem;
import net.mcreator.extrememonsters.item.DuplicatedMatterCatalystShardItem;
import net.mcreator.extrememonsters.item.DuplicatedLeatherItem;
import net.mcreator.extrememonsters.item.DuplicatedIronIngotItem;
import net.mcreator.extrememonsters.item.DuplicatedInfernoMatterItem;
import net.mcreator.extrememonsters.item.DuplicatedGoldIngotItem;
import net.mcreator.extrememonsters.item.DuplicatedDragonEggChunkItem;
import net.mcreator.extrememonsters.item.DuplicatedDiamondItem;
import net.mcreator.extrememonsters.item.DuplicatedDarkMatterPelletItem;
import net.mcreator.extrememonsters.item.DuplicatedBlackHoleMatterItem;
import net.mcreator.extrememonsters.item.DragonMatterSwordItem;
import net.mcreator.extrememonsters.item.DragonMatterItem;
import net.mcreator.extrememonsters.item.DragonMatterIngotItem;
import net.mcreator.extrememonsters.item.DragonMatterHammerItem;
import net.mcreator.extrememonsters.item.DragonMatterFuelItem;
import net.mcreator.extrememonsters.item.DragonMatterCrystalMatrixIngotItem;
import net.mcreator.extrememonsters.item.DragonMatterChestPieceItem;
import net.mcreator.extrememonsters.item.DragonMatterBandAidItem;
import net.mcreator.extrememonsters.item.DragonMatterArmorItem;
import net.mcreator.extrememonsters.item.DragonMatterAppleItem;
import net.mcreator.extrememonsters.item.DisposableHyperMobDesignatorItem;
import net.mcreator.extrememonsters.item.DenseRedstone5Item;
import net.mcreator.extrememonsters.item.DenseRedstone4Item;
import net.mcreator.extrememonsters.item.DenseRedstone3Item;
import net.mcreator.extrememonsters.item.DenseRedstone2Item;
import net.mcreator.extrememonsters.item.DenseRedstone1Item;
import net.mcreator.extrememonsters.item.DenseQuartz5Item;
import net.mcreator.extrememonsters.item.DenseQuartz4Item;
import net.mcreator.extrememonsters.item.DenseQuartz3Item;
import net.mcreator.extrememonsters.item.DenseQuartz2Item;
import net.mcreator.extrememonsters.item.DenseQuartz1Item;
import net.mcreator.extrememonsters.item.DenseNetheriteIngot5Item;
import net.mcreator.extrememonsters.item.DenseNetheriteIngot4Item;
import net.mcreator.extrememonsters.item.DenseNetheriteIngot3Item;
import net.mcreator.extrememonsters.item.DenseNetheriteIngot2Item;
import net.mcreator.extrememonsters.item.DenseNetheriteIngot1Item;
import net.mcreator.extrememonsters.item.DenseIronIngot5Item;
import net.mcreator.extrememonsters.item.DenseIronIngot4Item;
import net.mcreator.extrememonsters.item.DenseIronIngot3Item;
import net.mcreator.extrememonsters.item.DenseIronIngot2Item;
import net.mcreator.extrememonsters.item.DenseIronIngot1Item;
import net.mcreator.extrememonsters.item.DenseGoldIngot5Item;
import net.mcreator.extrememonsters.item.DenseGoldIngot4Item;
import net.mcreator.extrememonsters.item.DenseGoldIngot3Item;
import net.mcreator.extrememonsters.item.DenseGoldIngot2Item;
import net.mcreator.extrememonsters.item.DenseGoldIngot1Item;
import net.mcreator.extrememonsters.item.DenseDiamond5Item;
import net.mcreator.extrememonsters.item.DenseDiamond4Item;
import net.mcreator.extrememonsters.item.DenseDiamond3Item;
import net.mcreator.extrememonsters.item.DenseDiamond2Item;
import net.mcreator.extrememonsters.item.DenseDiamond1Item;
import net.mcreator.extrememonsters.item.DenseCopperIngot5Item;
import net.mcreator.extrememonsters.item.DenseCopperIngot4Item;
import net.mcreator.extrememonsters.item.DenseCopperIngot3Item;
import net.mcreator.extrememonsters.item.DenseCopperIngot2Item;
import net.mcreator.extrememonsters.item.DenseCopperIngot1Item;
import net.mcreator.extrememonsters.item.DenseCoal5Item;
import net.mcreator.extrememonsters.item.DenseCoal4Item;
import net.mcreator.extrememonsters.item.DenseCoal3Item;
import net.mcreator.extrememonsters.item.DenseCoal2Item;
import net.mcreator.extrememonsters.item.DenseCoal1Item;
import net.mcreator.extrememonsters.item.DarkMatterSwordItem;
import net.mcreator.extrememonsters.item.DarkMatterItem;
import net.mcreator.extrememonsters.item.DarkMatterIngotItem;
import net.mcreator.extrememonsters.item.DarkMatterHammerItem;
import net.mcreator.extrememonsters.item.DarkMatterFuelItem;
import net.mcreator.extrememonsters.item.DarkMatterFelletItem;
import net.mcreator.extrememonsters.item.DarkMatterExpBottleItem;
import net.mcreator.extrememonsters.item.DarkMatterDaggerItem;
import net.mcreator.extrememonsters.item.DarkMatterCrystalMatrixIngotItem;
import net.mcreator.extrememonsters.item.DarkMatterBombItem;
import net.mcreator.extrememonsters.item.DarkMatterBandAidItem;
import net.mcreator.extrememonsters.item.DarkMatterArmorItem;
import net.mcreator.extrememonsters.item.DarkMatterAppleItem;
import net.mcreator.extrememonsters.item.DaggerForTrackerItem;
import net.mcreator.extrememonsters.item.CondensedSolarResiduumItem;
import net.mcreator.extrememonsters.item.CompressionUpgrade3Item;
import net.mcreator.extrememonsters.item.CompressionUpgrade2Item;
import net.mcreator.extrememonsters.item.CompressionUpgrade1Item;
import net.mcreator.extrememonsters.item.CombinedPassItem;
import net.mcreator.extrememonsters.item.CollapsedRedstoneItem;
import net.mcreator.extrememonsters.item.CollapsedQuartzItem;
import net.mcreator.extrememonsters.item.CollapsedNetheriteIngotItem;
import net.mcreator.extrememonsters.item.CollapsedIronIngotItem;
import net.mcreator.extrememonsters.item.CollapsedGoldIngotItem;
import net.mcreator.extrememonsters.item.CollapsedDiamondItem;
import net.mcreator.extrememonsters.item.CollapsedCopperIngotItem;
import net.mcreator.extrememonsters.item.CollapsedCoalItem;
import net.mcreator.extrememonsters.item.BlackMatterIngotItem;
import net.mcreator.extrememonsters.item.BlackHoleMatterSwordItem;
import net.mcreator.extrememonsters.item.BlackHoleMatterStickItem;
import net.mcreator.extrememonsters.item.BlackHoleMatterShieldItem;
import net.mcreator.extrememonsters.item.BlackHoleMatterLaserEmitterItem;
import net.mcreator.extrememonsters.item.BlackHoleMatterItem;
import net.mcreator.extrememonsters.item.BlackHoleMatterHammerItem;
import net.mcreator.extrememonsters.item.BlackHoleMatterFuelItem;
import net.mcreator.extrememonsters.item.BlackHoleMatterExpBottleItem;
import net.mcreator.extrememonsters.item.BlackHoleMatterCrystalMatrixIngotItem;
import net.mcreator.extrememonsters.item.BlackHoleMatterBandAidItem;
import net.mcreator.extrememonsters.item.BlackHoleMatterArmorItem;
import net.mcreator.extrememonsters.item.BlackHoleMatterAppleItem;
import net.mcreator.extrememonsters.item.BlackHoleBombItem;
import net.mcreator.extrememonsters.item.AssemblerUpgrade3Item;
import net.mcreator.extrememonsters.item.AssemblerUpgrade2Item;
import net.mcreator.extrememonsters.item.AssemblerUpgrade1Item;
import net.mcreator.extrememonsters.item.AscendedEvasionAmuletItem;
import net.mcreator.extrememonsters.item.ArrowRemoverItem;
import net.mcreator.extrememonsters.item.AmmoExtractorItem;
import net.mcreator.extrememonsters.item.AllthematteriumIngotItem;
import net.mcreator.extrememonsters.item.AllthehyperiumIngotItem;
import net.mcreator.extrememonsters.item.AbyssalCountDownItem;
import net.mcreator.extrememonsters.block.display.TrackerContainmentCageDisplayItem;
import net.mcreator.extrememonsters.block.display.PlanetaryRegulatorDisplayItem;
import net.mcreator.extrememonsters.block.display.FictionalPlanetDisplayItem;
import net.mcreator.extrememonsters.block.display.ContainedSuperTrackerDisplayItem;
import net.mcreator.extrememonsters.block.display.ArtificialSunDisplayItem;
import net.mcreator.extrememonsters.block.display.ArtificialNeutronStarDisplayItem;
import net.mcreator.extrememonsters.ExtremeMonstersMod;

@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD)
public class ExtremeMonstersModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(ExtremeMonstersMod.MODID);
	public static final DeferredItem<Item> START_EXTREME = REGISTRY.register("start_extreme", StartExtremeItem::new);
	public static final DeferredItem<Item> TRACKER_SPAWN_EGG = REGISTRY.register("tracker_spawn_egg", () -> new DeferredSpawnEggItem(ExtremeMonstersModEntities.TRACKER, -16777216, -13421773, new Item.Properties()));
	public static final DeferredItem<Item> TRACKER_SPAWN_DETECTOR = REGISTRY.register("tracker_spawn_detector", TrackerSpawnDetectorItem::new);
	public static final DeferredItem<Item> FLYING_TRACKER_SPAWN_EGG = REGISTRY.register("flying_tracker_spawn_egg", () -> new DeferredSpawnEggItem(ExtremeMonstersModEntities.FLYING_TRACKER, -16777216, -13421773, new Item.Properties()));
	public static final DeferredItem<Item> HYPER_MOB_DESIGNATOR = REGISTRY.register("hyper_mob_designator", HyperMobDesignatorItem::new);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER = REGISTRY.register("black_hole_matter", BlackHoleMatterItem::new);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_BLOCK = block(ExtremeMonstersModBlocks.BLACK_HOLE_MATTER_BLOCK);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_GLASS = block(ExtremeMonstersModBlocks.BLACK_HOLE_MATTER_GLASS);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_BLOCK_1X = block(ExtremeMonstersModBlocks.BLACK_HOLE_MATTER_BLOCK_1X);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_BLOCK_2X = block(ExtremeMonstersModBlocks.BLACK_HOLE_MATTER_BLOCK_2X);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_BLOCK_3X = block(ExtremeMonstersModBlocks.BLACK_HOLE_MATTER_BLOCK_3X);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_SWORD = REGISTRY.register("black_hole_matter_sword", BlackHoleMatterSwordItem::new);
	public static final DeferredItem<Item> HYPER_ROTTEN_FLESH = REGISTRY.register("hyper_rotten_flesh", HyperRottenFleshItem::new);
	public static final DeferredItem<Item> HYPER_BONE = REGISTRY.register("hyper_bone", HyperBoneItem::new);
	public static final DeferredItem<Item> TRACKERS_ABYSS = REGISTRY.register("trackers_abyss", TrackersAbyssItem::new);
	public static final DeferredItem<Item> TOTEM_OF_BLACKHOLE = REGISTRY.register("totem_of_blackhole", TotemOfBlackholeItem::new);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_SHIELD = REGISTRY.register("black_hole_matter_shield", BlackHoleMatterShieldItem::new);
	public static final DeferredItem<Item> ARROW_REMOVER = REGISTRY.register("arrow_remover", ArrowRemoverItem::new);
	public static final DeferredItem<Item> DARK_MATTER_GENERATOR = block(ExtremeMonstersModBlocks.DARK_MATTER_GENERATOR);
	public static final DeferredItem<Item> DARK_MATTER_FELLET = REGISTRY.register("dark_matter_fellet", DarkMatterFelletItem::new);
	public static final DeferredItem<Item> HYPER_GUNPOWDER = REGISTRY.register("hyper_gunpowder", HyperGunpowderItem::new);
	public static final DeferredItem<Item> HYPER_STAFF = REGISTRY.register("hyper_staff", HyperStaffItem::new);
	public static final DeferredItem<Item> BLACK_MATTER_INGOT = REGISTRY.register("black_matter_ingot", BlackMatterIngotItem::new);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_SOLAR_PLANEL = block(ExtremeMonstersModBlocks.BLACK_HOLE_MATTER_SOLAR_PLANEL);
	public static final DeferredItem<Item> DAGGER_FOR_TRACKER = REGISTRY.register("dagger_for_tracker", DaggerForTrackerItem::new);
	public static final DeferredItem<Item> NETHERITE_FUSION_REACTOR = block(ExtremeMonstersModBlocks.NETHERITE_FUSION_REACTOR);
	public static final DeferredItem<Item> SOUL_COLLECTOR = REGISTRY.register("soul_collector", SoulCollectorItem::new);
	public static final DeferredItem<Item> TRACKERS_SOUL = REGISTRY.register("trackers_soul", TrackersSoulItem::new);
	public static final DeferredItem<Item> SOUL_INSERT_MACHINE = block(ExtremeMonstersModBlocks.SOUL_INSERT_MACHINE);
	public static final DeferredItem<Item> SPEED_UPGRADE_1 = REGISTRY.register("speed_upgrade_1", SpeedUpgrade1Item::new);
	public static final DeferredItem<Item> SIMULATION_CHAMBER = block(ExtremeMonstersModBlocks.SIMULATION_CHAMBER);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_ASSEMBLER = block(ExtremeMonstersModBlocks.BLACK_HOLE_MATTER_ASSEMBLER);
	public static final DeferredItem<Item> AWKWARD_MACHINE_FRAME = block(ExtremeMonstersModBlocks.AWKWARD_MACHINE_FRAME);
	public static final DeferredItem<Item> BASIC_MACHINE_FRAME = block(ExtremeMonstersModBlocks.BASIC_MACHINE_FRAME);
	public static final DeferredItem<Item> MOB_SEDUCE = block(ExtremeMonstersModBlocks.MOB_SEDUCE);
	public static final DeferredItem<Item> CREATIVE_GENERATOR = block(ExtremeMonstersModBlocks.CREATIVE_GENERATOR);
	public static final DeferredItem<Item> MATTER_CATALYST = REGISTRY.register("matter_catalyst", MatterCatalystItem::new);
	public static final DeferredItem<Item> MATTER_CATALYST_SHARD = REGISTRY.register("matter_catalyst_shard", MatterCatalystShardItem::new);
	public static final DeferredItem<Item> TRACKER_DEFENDER = block(ExtremeMonstersModBlocks.TRACKER_DEFENDER);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_RELAY = block(ExtremeMonstersModBlocks.BLACK_HOLE_MATTER_RELAY);
	public static final DeferredItem<Item> MATTER_FUSION_REACTOR_1 = block(ExtremeMonstersModBlocks.MATTER_FUSION_REACTOR_1);
	public static final DeferredItem<Item> MATTER_CATALYST_MAKER = block(ExtremeMonstersModBlocks.MATTER_CATALYST_MAKER);
	public static final DeferredItem<Item> MATTER_CATALYST_FOUNDATION = block(ExtremeMonstersModBlocks.MATTER_CATALYST_FOUNDATION);
	public static final DeferredItem<Item> DARK_MATTER = REGISTRY.register("dark_matter", DarkMatterItem::new);
	public static final DeferredItem<Item> DARK_MATTER_SWORD = REGISTRY.register("dark_matter_sword", DarkMatterSwordItem::new);
	public static final DeferredItem<Item> DARK_MATTER_BLOCK = block(ExtremeMonstersModBlocks.DARK_MATTER_BLOCK);
	public static final DeferredItem<Item> HYPER_ENSSENCE_1 = REGISTRY.register("hyper_enssence_1", HyperEnssence1Item::new);
	public static final DeferredItem<Item> ADVANCED_MACHINE_FRAME = block(ExtremeMonstersModBlocks.ADVANCED_MACHINE_FRAME);
	public static final DeferredItem<Item> DARK_MATTER_FUEL = REGISTRY.register("dark_matter_fuel", DarkMatterFuelItem::new);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_FUEL = REGISTRY.register("black_hole_matter_fuel", BlackHoleMatterFuelItem::new);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_ARMOR_HELMET = REGISTRY.register("black_hole_matter_armor_helmet", BlackHoleMatterArmorItem.Helmet::new);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_ARMOR_CHESTPLATE = REGISTRY.register("black_hole_matter_armor_chestplate", BlackHoleMatterArmorItem.Chestplate::new);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_ARMOR_LEGGINGS = REGISTRY.register("black_hole_matter_armor_leggings", BlackHoleMatterArmorItem.Leggings::new);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_ARMOR_BOOTS = REGISTRY.register("black_hole_matter_armor_boots", BlackHoleMatterArmorItem.Boots::new);
	public static final DeferredItem<Item> DARK_MATTER_INGOT = REGISTRY.register("dark_matter_ingot", DarkMatterIngotItem::new);
	public static final DeferredItem<Item> DARK_MATTER_ARMOR_HELMET = REGISTRY.register("dark_matter_armor_helmet", DarkMatterArmorItem.Helmet::new);
	public static final DeferredItem<Item> DARK_MATTER_ARMOR_CHESTPLATE = REGISTRY.register("dark_matter_armor_chestplate", DarkMatterArmorItem.Chestplate::new);
	public static final DeferredItem<Item> DARK_MATTER_ARMOR_LEGGINGS = REGISTRY.register("dark_matter_armor_leggings", DarkMatterArmorItem.Leggings::new);
	public static final DeferredItem<Item> DARK_MATTER_ARMOR_BOOTS = REGISTRY.register("dark_matter_armor_boots", DarkMatterArmorItem.Boots::new);
	public static final DeferredItem<Item> HYPER_ZOMBIES_SOUL = REGISTRY.register("hyper_zombies_soul", HyperZombiesSoulItem::new);
	public static final DeferredItem<Item> TRACKER_DEFENDER_MK_2 = block(ExtremeMonstersModBlocks.TRACKER_DEFENDER_MK_2);
	public static final DeferredItem<Item> DARK_MATTER_RELAY = block(ExtremeMonstersModBlocks.DARK_MATTER_RELAY);
	public static final DeferredItem<Item> COMBUSTION_GENERATOR = block(ExtremeMonstersModBlocks.COMBUSTION_GENERATOR);
	public static final DeferredItem<Item> DARK_MATTER_SOLAR_PANEL = block(ExtremeMonstersModBlocks.DARK_MATTER_SOLAR_PANEL);
	public static final DeferredItem<Item> SPIDER_EGG = block(ExtremeMonstersModBlocks.SPIDER_EGG);
	public static final DeferredItem<Item> HYPER_SPIDER_EYE = REGISTRY.register("hyper_spider_eye", HyperSpiderEyeItem::new);
	public static final DeferredItem<Item> NETHER_PASS = REGISTRY.register("nether_pass", NetherPassItem::new);
	public static final DeferredItem<Item> HYPER_SKELETONS_SOUL = REGISTRY.register("hyper_skeletons_soul", HyperSkeletonsSoulItem::new);
	public static final DeferredItem<Item> HYPER_CREEPERS_SOUL = REGISTRY.register("hyper_creepers_soul", HyperCreepersSoulItem::new);
	public static final DeferredItem<Item> COMBUSTION_GENERATOR_MK_2 = block(ExtremeMonstersModBlocks.COMBUSTION_GENERATOR_MK_2);
	public static final DeferredItem<Item> MATTER_FUSION_REACTOR_2 = block(ExtremeMonstersModBlocks.MATTER_FUSION_REACTOR_2);
	public static final DeferredItem<Item> HYPER_SPIDERS_SOUL = REGISTRY.register("hyper_spiders_soul", HyperSpidersSoulItem::new);
	public static final DeferredItem<Item> DUPLICATOR = block(ExtremeMonstersModBlocks.DUPLICATOR);
	public static final DeferredItem<Item> DUPLICATED_BLACK_HOLE_MATTER = REGISTRY.register("duplicated_black_hole_matter", DuplicatedBlackHoleMatterItem::new);
	public static final DeferredItem<Item> DUPLICATED_DARK_MATTER_PELLET = REGISTRY.register("duplicated_dark_matter_pellet", DuplicatedDarkMatterPelletItem::new);
	public static final DeferredItem<Item> HYPER_GOLD_NUGGET = REGISTRY.register("hyper_gold_nugget", HyperGoldNuggetItem::new);
	public static final DeferredItem<Item> HYPER_GOLD_INGOT = REGISTRY.register("hyper_gold_ingot", HyperGoldIngotItem::new);
	public static final DeferredItem<Item> HYPER_GOLD_PICKAXE = REGISTRY.register("hyper_gold_pickaxe", HyperGoldPickaxeItem::new);
	public static final DeferredItem<Item> MOB_ATTACKER = block(ExtremeMonstersModBlocks.MOB_ATTACKER);
	public static final DeferredItem<Item> DUPLICATED_MATTER_CATALYST_SHARD = REGISTRY.register("duplicated_matter_catalyst_shard", DuplicatedMatterCatalystShardItem::new);
	public static final DeferredItem<Item> PROJECTILE_REMOVER = block(ExtremeMonstersModBlocks.PROJECTILE_REMOVER);
	public static final DeferredItem<Item> DARK_MATTER_ASSEMBLER = block(ExtremeMonstersModBlocks.DARK_MATTER_ASSEMBLER);
	public static final DeferredItem<Item> CLEVER_MACHINE_FRAME = block(ExtremeMonstersModBlocks.CLEVER_MACHINE_FRAME);
	public static final DeferredItem<Item> DIAMOND_GENERATOR = block(ExtremeMonstersModBlocks.DIAMOND_GENERATOR);
	public static final DeferredItem<Item> SPEED_UPGRADE_2 = REGISTRY.register("speed_upgrade_2", SpeedUpgrade2Item::new);
	public static final DeferredItem<Item> HYPER_ZOMBIFIED_PIGLINS_SOUL = REGISTRY.register("hyper_zombified_piglins_soul", HyperZombifiedPiglinsSoulItem::new);
	public static final DeferredItem<Item> INFINITE_LAVA_AMULET = REGISTRY.register("infinite_lava_amulet", InfiniteLavaAmuletItem::new);
	public static final DeferredItem<Item> INFINITE_WATER_AMULET = REGISTRY.register("infinite_water_amulet", InfiniteWaterAmuletItem::new);
	public static final DeferredItem<Item> NOMAL_ARROW_BARRAGER = REGISTRY.register("nomal_arrow_barrager", NomalArrowBarragerItem::new);
	public static final DeferredItem<Item> EVASION_AMULET = REGISTRY.register("evasion_amulet", EvasionAmuletItem::new);
	public static final DeferredItem<Item> BLACK_HOLE_BOMB = REGISTRY.register("black_hole_bomb", BlackHoleBombItem::new);
	public static final DeferredItem<Item> DARK_MATTER_BOMB = REGISTRY.register("dark_matter_bomb", DarkMatterBombItem::new);
	public static final DeferredItem<Item> MOB_DISRUPTOR = REGISTRY.register("mob_disruptor", MobDisruptorItem::new);
	public static final DeferredItem<Item> DARK_MATTER_APPLE = REGISTRY.register("dark_matter_apple", DarkMatterAppleItem::new);
	public static final DeferredItem<Item> ABYSSAL_COUNT_DOWN = REGISTRY.register("abyssal_count_down", AbyssalCountDownItem::new);
	public static final DeferredItem<Item> SUPER_MAGMA = block(ExtremeMonstersModBlocks.SUPER_MAGMA);
	public static final DeferredItem<Item> HYPER_MAGMA_CREAM = REGISTRY.register("hyper_magma_cream", HyperMagmaCreamItem::new);
	public static final DeferredItem<Item> INFERNO_MATTER = REGISTRY.register("inferno_matter", InfernoMatterItem::new);
	public static final DeferredItem<Item> INFERNO_MATTER_FUEL = REGISTRY.register("inferno_matter_fuel", InfernoMatterFuelItem::new);
	public static final DeferredItem<Item> INFERNO_MATTER_SWORD = REGISTRY.register("inferno_matter_sword", InfernoMatterSwordItem::new);
	public static final DeferredItem<Item> INFERNO_MATTER_BLOCK = block(ExtremeMonstersModBlocks.INFERNO_MATTER_BLOCK);
	public static final DeferredItem<Item> TRACKER_DEFENDER_MK_3 = block(ExtremeMonstersModBlocks.TRACKER_DEFENDER_MK_3);
	public static final DeferredItem<Item> INFERNO_MATTER_SOLAR_PANEL = block(ExtremeMonstersModBlocks.INFERNO_MATTER_SOLAR_PANEL);
	public static final DeferredItem<Item> INFERNO_MATTER_RELAY = block(ExtremeMonstersModBlocks.INFERNO_MATTER_RELAY);
	public static final DeferredItem<Item> TRACKERS_VOID = REGISTRY.register("trackers_void", TrackersVoidItem::new);
	public static final DeferredItem<Item> INFERNO_MATTER_APPLE = REGISTRY.register("inferno_matter_apple", InfernoMatterAppleItem::new);
	public static final DeferredItem<Item> DUPLICATED_INFERNO_MATTER = REGISTRY.register("duplicated_inferno_matter", DuplicatedInfernoMatterItem::new);
	public static final DeferredItem<Item> INFERNO_MATTER_SHARD = REGISTRY.register("inferno_matter_shard", InfernoMatterShardItem::new);
	public static final DeferredItem<Item> TRACKER_AVOIDER = REGISTRY.register("tracker_avoider", TrackerAvoiderItem::new);
	public static final DeferredItem<Item> SINGULARITY = REGISTRY.register("singularity", SingularityItem::new);
	public static final DeferredItem<Item> ETERNAL_DARK_MATTER_APPLE = REGISTRY.register("eternal_dark_matter_apple", EternalDarkMatterAppleItem::new);
	public static final DeferredItem<Item> DUPLICATED_IRON_INGOT = REGISTRY.register("duplicated_iron_ingot", DuplicatedIronIngotItem::new);
	public static final DeferredItem<Item> DUPLICATED_GOLD_INGOT = REGISTRY.register("duplicated_gold_ingot", DuplicatedGoldIngotItem::new);
	public static final DeferredItem<Item> DUPLICATED_DIAMOND = REGISTRY.register("duplicated_diamond", DuplicatedDiamondItem::new);
	public static final DeferredItem<Item> INFERNO_MATTER_BOMB = REGISTRY.register("inferno_matter_bomb", InfernoMatterBombItem::new);
	public static final DeferredItem<Item> INFERNO_MATTER_ARMOR_HELMET = REGISTRY.register("inferno_matter_armor_helmet", InfernoMatterArmorItem.Helmet::new);
	public static final DeferredItem<Item> INFERNO_MATTER_ARMOR_CHESTPLATE = REGISTRY.register("inferno_matter_armor_chestplate", InfernoMatterArmorItem.Chestplate::new);
	public static final DeferredItem<Item> INFERNO_MATTER_ARMOR_LEGGINGS = REGISTRY.register("inferno_matter_armor_leggings", InfernoMatterArmorItem.Leggings::new);
	public static final DeferredItem<Item> INFERNO_MATTER_ARMOR_BOOTS = REGISTRY.register("inferno_matter_armor_boots", InfernoMatterArmorItem.Boots::new);
	public static final DeferredItem<Item> RING_OF_FLIGHT = REGISTRY.register("ring_of_flight", RingOfFlightItem::new);
	public static final DeferredItem<Item> SMELTING_STICK = REGISTRY.register("smelting_stick", SmeltingStickItem::new);
	public static final DeferredItem<Item> COMBUSTION_GENERATOR_MK_3 = block(ExtremeMonstersModBlocks.COMBUSTION_GENERATOR_MK_3);
	public static final DeferredItem<Item> HYPER_WITHERED_BONE = REGISTRY.register("hyper_withered_bone", HyperWitheredBoneItem::new);
	public static final DeferredItem<Item> INFERNO_MATTER_INGOT = REGISTRY.register("inferno_matter_ingot", InfernoMatterIngotItem::new);
	public static final DeferredItem<Item> MATTER_FUSION_REACTOR_3 = block(ExtremeMonstersModBlocks.MATTER_FUSION_REACTOR_3);
	public static final DeferredItem<Item> HYPER_BLAZE_ROD = REGISTRY.register("hyper_blaze_rod", HyperBlazeRodItem::new);
	public static final DeferredItem<Item> HYPER_ENSSENCE_2 = REGISTRY.register("hyper_enssence_2", HyperEnssence2Item::new);
	public static final DeferredItem<Item> END_PASS = REGISTRY.register("end_pass", EndPassItem::new);
	public static final DeferredItem<Item> HYPER_WITHER_SKELETONS_SOUL = REGISTRY.register("hyper_wither_skeletons_soul", HyperWitherSkeletonsSoulItem::new);
	public static final DeferredItem<Item> HYPER_BLAZES_SOUL = REGISTRY.register("hyper_blazes_soul", HyperBlazesSoulItem::new);
	public static final DeferredItem<Item> MATTER_CATALYST_FOUNDATION_1X = block(ExtremeMonstersModBlocks.MATTER_CATALYST_FOUNDATION_1X);
	public static final DeferredItem<Item> MATTER_CATALYST_FOUNDATION_2X = block(ExtremeMonstersModBlocks.MATTER_CATALYST_FOUNDATION_2X);
	public static final DeferredItem<Item> MATTER_CATALYST_FOUNDATION_3X = block(ExtremeMonstersModBlocks.MATTER_CATALYST_FOUNDATION_3X);
	public static final DeferredItem<Item> DUPLICATED_BEDROCK = block(ExtremeMonstersModBlocks.DUPLICATED_BEDROCK);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_APPLE = REGISTRY.register("black_hole_matter_apple", BlackHoleMatterAppleItem::new);
	public static final DeferredItem<Item> ETERNAL_BLACK_HOLE_MATTER_APPLE = REGISTRY.register("eternal_black_hole_matter_apple", EternalBlackHoleMatterAppleItem::new);
	public static final DeferredItem<Item> SOUL_INSERT_MACHINE_MK_2 = block(ExtremeMonstersModBlocks.SOUL_INSERT_MACHINE_MK_2);
	public static final DeferredItem<Item> SIMULATION_CHAMBER_MK_2 = block(ExtremeMonstersModBlocks.SIMULATION_CHAMBER_MK_2);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_BAND_AID = REGISTRY.register("black_hole_matter_band_aid", BlackHoleMatterBandAidItem::new);
	public static final DeferredItem<Item> DARK_MATTER_BAND_AID = REGISTRY.register("dark_matter_band_aid", DarkMatterBandAidItem::new);
	public static final DeferredItem<Item> SOUL_INSERT_MACHINE_MK_3 = block(ExtremeMonstersModBlocks.SOUL_INSERT_MACHINE_MK_3);
	public static final DeferredItem<Item> SIMULATION_CHAMBER_MK_3 = block(ExtremeMonstersModBlocks.SIMULATION_CHAMBER_MK_3);
	public static final DeferredItem<Item> DARK_MATTER_GENERATOR_MK_2 = block(ExtremeMonstersModBlocks.DARK_MATTER_GENERATOR_MK_2);
	public static final DeferredItem<Item> DARK_MATTER_GENERATOR_MK_3 = block(ExtremeMonstersModBlocks.DARK_MATTER_GENERATOR_MK_3);
	public static final DeferredItem<Item> FORCE_EMITTER = block(ExtremeMonstersModBlocks.FORCE_EMITTER);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_EXP_BOTTLE = REGISTRY.register("black_hole_matter_exp_bottle", BlackHoleMatterExpBottleItem::new);
	public static final DeferredItem<Item> DARK_MATTER_EXP_BOTTLE = REGISTRY.register("dark_matter_exp_bottle", DarkMatterExpBottleItem::new);
	public static final DeferredItem<Item> INFERNO_MATTER_EXP_BOTTLE = REGISTRY.register("inferno_matter_exp_bottle", InfernoMatterExpBottleItem::new);
	public static final DeferredItem<Item> HYPER_ENDER_PEARL = REGISTRY.register("hyper_ender_pearl", HyperEnderPearlItem::new);
	public static final DeferredItem<Item> UPGRADED_ARROW_REMOVER = REGISTRY.register("upgraded_arrow_remover", UpgradedArrowRemoverItem::new);
	public static final DeferredItem<Item> HYPER_DRAGON_SKIN = REGISTRY.register("hyper_dragon_skin", HyperDragonSkinItem::new);
	public static final DeferredItem<Item> DRAGON_MATTER = REGISTRY.register("dragon_matter", DragonMatterItem::new);
	public static final DeferredItem<Item> DRAGON_MATTER_SWORD = REGISTRY.register("dragon_matter_sword", DragonMatterSwordItem::new);
	public static final DeferredItem<Item> DRAGON_MATTER_ARMOR_HELMET = REGISTRY.register("dragon_matter_armor_helmet", DragonMatterArmorItem.Helmet::new);
	public static final DeferredItem<Item> DRAGON_MATTER_ARMOR_CHESTPLATE = REGISTRY.register("dragon_matter_armor_chestplate", DragonMatterArmorItem.Chestplate::new);
	public static final DeferredItem<Item> DRAGON_MATTER_ARMOR_LEGGINGS = REGISTRY.register("dragon_matter_armor_leggings", DragonMatterArmorItem.Leggings::new);
	public static final DeferredItem<Item> DRAGON_MATTER_ARMOR_BOOTS = REGISTRY.register("dragon_matter_armor_boots", DragonMatterArmorItem.Boots::new);
	public static final DeferredItem<Item> MIRROR_OF_DESPAIR = REGISTRY.register("mirror_of_despair", MirrorOfDespairItem::new);
	public static final DeferredItem<Item> DARK_MATTER_DAGGER = REGISTRY.register("dark_matter_dagger", DarkMatterDaggerItem::new);
	public static final DeferredItem<Item> DRAGON_MATTER_BLOCK = block(ExtremeMonstersModBlocks.DRAGON_MATTER_BLOCK);
	public static final DeferredItem<Item> ULTIMATE_CATALYST = REGISTRY.register("ultimate_catalyst", UltimateCatalystItem::new);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_BLOCK_4X = block(ExtremeMonstersModBlocks.BLACK_HOLE_MATTER_BLOCK_4X);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_BLOCK_5X = block(ExtremeMonstersModBlocks.BLACK_HOLE_MATTER_BLOCK_5X);
	public static final DeferredItem<Item> DRAGON_MATTER_CHEST_PIECE = REGISTRY.register("dragon_matter_chest_piece", DragonMatterChestPieceItem::new);
	public static final DeferredItem<Item> HYPER_ESSENCE_3 = REGISTRY.register("hyper_essence_3", HyperEssence3Item::new);
	public static final DeferredItem<Item> DRAGON_MATTER_SOLAR_PANEL = block(ExtremeMonstersModBlocks.DRAGON_MATTER_SOLAR_PANEL);
	public static final DeferredItem<Item> TRACKER_DEFENDER_MK_4 = block(ExtremeMonstersModBlocks.TRACKER_DEFENDER_MK_4);
	public static final DeferredItem<Item> DRAGON_MACHINE_FRAME = block(ExtremeMonstersModBlocks.DRAGON_MACHINE_FRAME);
	public static final DeferredItem<Item> OMEGA_D_CORE_STABILIZER = block(ExtremeMonstersModBlocks.OMEGA_D_CORE_STABILIZER);
	public static final DeferredItem<Item> OMEGA_D_CORE = block(ExtremeMonstersModBlocks.OMEGA_D_CORE);
	public static final DeferredItem<Item> OMEGA_WRENCH = REGISTRY.register("omega_wrench", OmegaWrenchItem::new);
	public static final DeferredItem<Item> DRAGON_MATTER_RELAY = block(ExtremeMonstersModBlocks.DRAGON_MATTER_RELAY);
	public static final DeferredItem<Item> INFERNO_ENERGY_CUBE = block(ExtremeMonstersModBlocks.INFERNO_ENERGY_CUBE);
	public static final DeferredItem<Item> DRAGON_ENERGY_CUBE = block(ExtremeMonstersModBlocks.DRAGON_ENERGY_CUBE);
	public static final DeferredItem<Item> EXPLOSIVE_EMITTER = REGISTRY.register("explosive_emitter", ExplosiveEmitterItem::new);
	public static final DeferredItem<Item> MOB_IMMOBILIZER = REGISTRY.register("mob_immobilizer", MobImmobilizerItem::new);
	public static final DeferredItem<Item> ICE_MAKER = block(ExtremeMonstersModBlocks.ICE_MAKER);
	public static final DeferredItem<Item> DRAGON_INCUBATOR = block(ExtremeMonstersModBlocks.DRAGON_INCUBATOR);
	public static final DeferredItem<Item> ENDER_DRAGON_IN_THE_BOTTLE = REGISTRY.register("ender_dragon_in_the_bottle", EnderDragonInTheBottleItem::new);
	public static final DeferredItem<Item> HYPER_ENDER_DRAGON_IN_THE_BOTTLE = REGISTRY.register("hyper_ender_dragon_in_the_bottle", HyperEnderDragonInTheBottleItem::new);
	public static final DeferredItem<Item> DUPLICATED_DRAGON_EGG_CHUNK = REGISTRY.register("duplicated_dragon_egg_chunk", DuplicatedDragonEggChunkItem::new);
	public static final DeferredItem<Item> HYPER_ENDERMANS_SOUL = REGISTRY.register("hyper_endermans_soul", HyperEndermansSoulItem::new);
	public static final DeferredItem<Item> DRAGON_MATTER_INGOT = REGISTRY.register("dragon_matter_ingot", DragonMatterIngotItem::new);
	public static final DeferredItem<Item> HYPER_NETHER_STAR = REGISTRY.register("hyper_nether_star", HyperNetherStarItem::new);
	public static final DeferredItem<Item> WITHER_MATTER = REGISTRY.register("wither_matter", WitherMatterItem::new);
	public static final DeferredItem<Item> WITHER_MATTER_SWORD = REGISTRY.register("wither_matter_sword", WitherMatterSwordItem::new);
	public static final DeferredItem<Item> WITHER_MATTER_ARMOR_HELMET = REGISTRY.register("wither_matter_armor_helmet", WitherMatterArmorItem.Helmet::new);
	public static final DeferredItem<Item> WITHER_MATTER_ARMOR_CHESTPLATE = REGISTRY.register("wither_matter_armor_chestplate", WitherMatterArmorItem.Chestplate::new);
	public static final DeferredItem<Item> WITHER_MATTER_ARMOR_LEGGINGS = REGISTRY.register("wither_matter_armor_leggings", WitherMatterArmorItem.Leggings::new);
	public static final DeferredItem<Item> WITHER_MATTER_ARMOR_BOOTS = REGISTRY.register("wither_matter_armor_boots", WitherMatterArmorItem.Boots::new);
	public static final DeferredItem<Item> WITHER_MATTER_INGOT = REGISTRY.register("wither_matter_ingot", WitherMatterIngotItem::new);
	public static final DeferredItem<Item> WITHER_MATTER_BLOCK = block(ExtremeMonstersModBlocks.WITHER_MATTER_BLOCK);
	public static final DeferredItem<Item> WITHER_ENERGY_CUBE = block(ExtremeMonstersModBlocks.WITHER_ENERGY_CUBE);
	public static final DeferredItem<Item> COMBUSTION_GENERATOR_MK_4 = block(ExtremeMonstersModBlocks.COMBUSTION_GENERATOR_MK_4);
	public static final DeferredItem<Item> MATTER_FUSION_REACTOR_4 = block(ExtremeMonstersModBlocks.MATTER_FUSION_REACTOR_4);
	public static final DeferredItem<Item> WITHER_MATTER_SOLAR_PANEL = block(ExtremeMonstersModBlocks.WITHER_MATTER_SOLAR_PANEL);
	public static final DeferredItem<Item> WITHER_MATTER_RELAY = block(ExtremeMonstersModBlocks.WITHER_MATTER_RELAY);
	public static final DeferredItem<Item> COMBUSTION_GENERATOR_MK_5 = block(ExtremeMonstersModBlocks.COMBUSTION_GENERATOR_MK_5);
	public static final DeferredItem<Item> MATTER_FUSION_REACTOR_5 = block(ExtremeMonstersModBlocks.MATTER_FUSION_REACTOR_5);
	public static final DeferredItem<Item> WIRELESS_AUTO_MENDER = block(ExtremeMonstersModBlocks.WIRELESS_AUTO_MENDER);
	public static final DeferredItem<Item> TRACKER_DEFENDER_MK_5 = block(ExtremeMonstersModBlocks.TRACKER_DEFENDER_MK_5);
	public static final DeferredItem<Item> ALLOY_SMELTER = block(ExtremeMonstersModBlocks.ALLOY_SMELTER);
	public static final DeferredItem<Item> ALLTHEMATTERIUM_INGOT = REGISTRY.register("allthematterium_ingot", AllthematteriumIngotItem::new);
	public static final DeferredItem<Item> STARS_SOUL = REGISTRY.register("stars_soul", StarsSoulItem::new);
	public static final DeferredItem<Item> HYPER_INGOT_1 = REGISTRY.register("hyper_ingot_1", HyperIngot1Item::new);
	public static final DeferredItem<Item> HYPER_INGOT_2 = REGISTRY.register("hyper_ingot_2", HyperIngot2Item::new);
	public static final DeferredItem<Item> HYPER_INGOT_3 = REGISTRY.register("hyper_ingot_3", HyperIngot3Item::new);
	public static final DeferredItem<Item> HYPER_DRAGON_INGOT = REGISTRY.register("hyper_dragon_ingot", HyperDragonIngotItem::new);
	public static final DeferredItem<Item> HYPER_WITHER_INGOT = REGISTRY.register("hyper_wither_ingot", HyperWitherIngotItem::new);
	public static final DeferredItem<Item> ALLTHEHYPERIUM_INGOT = REGISTRY.register("allthehyperium_ingot", AllthehyperiumIngotItem::new);
	public static final DeferredItem<Item> HYPER_GOLD_INGOT_BLOCK = block(ExtremeMonstersModBlocks.HYPER_GOLD_INGOT_BLOCK);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_INGOT_BLOCK = block(ExtremeMonstersModBlocks.BLACK_HOLE_MATTER_INGOT_BLOCK);
	public static final DeferredItem<Item> DARK_MATTER_INGOT_BLOCK = block(ExtremeMonstersModBlocks.DARK_MATTER_INGOT_BLOCK);
	public static final DeferredItem<Item> INFERNO_MATTER_INGOT_BLOCK = block(ExtremeMonstersModBlocks.INFERNO_MATTER_INGOT_BLOCK);
	public static final DeferredItem<Item> DRAGON_MATTER_INGOT_BLOCK = block(ExtremeMonstersModBlocks.DRAGON_MATTER_INGOT_BLOCK);
	public static final DeferredItem<Item> WITHER_MATTER_INGOT_BLOCK = block(ExtremeMonstersModBlocks.WITHER_MATTER_INGOT_BLOCK);
	public static final DeferredItem<Item> FIERY_SOUL_COLLECTOR = REGISTRY.register("fiery_soul_collector", FierySoulCollectorItem::new);
	public static final DeferredItem<Item> HYPER_MAGMA_CUBES_SOUL = REGISTRY.register("hyper_magma_cubes_soul", HyperMagmaCubesSoulItem::new);
	public static final DeferredItem<Item> QUANTUM_INFUSER = block(ExtremeMonstersModBlocks.QUANTUM_INFUSER);
	public static final DeferredItem<Item> ENERGY_STABILIZER = block(ExtremeMonstersModBlocks.ENERGY_STABILIZER);
	public static final DeferredItem<Item> PERFECT_MATTER_FOUNDATION = block(ExtremeMonstersModBlocks.PERFECT_MATTER_FOUNDATION);
	public static final DeferredItem<Item> PERFECT_MATTER = REGISTRY.register("perfect_matter", PerfectMatterItem::new);
	public static final DeferredItem<Item> PERFECT_MATTER_SWORD = REGISTRY.register("perfect_matter_sword", PerfectMatterSwordItem::new);
	public static final DeferredItem<Item> PERFECT_MATTER_ARMOR_HELMET = REGISTRY.register("perfect_matter_armor_helmet", PerfectMatterArmorItem.Helmet::new);
	public static final DeferredItem<Item> PERFECT_MATTER_ARMOR_CHESTPLATE = REGISTRY.register("perfect_matter_armor_chestplate", PerfectMatterArmorItem.Chestplate::new);
	public static final DeferredItem<Item> PERFECT_MATTER_ARMOR_LEGGINGS = REGISTRY.register("perfect_matter_armor_leggings", PerfectMatterArmorItem.Leggings::new);
	public static final DeferredItem<Item> PERFECT_MATTER_ARMOR_BOOTS = REGISTRY.register("perfect_matter_armor_boots", PerfectMatterArmorItem.Boots::new);
	public static final DeferredItem<Item> PERFECT_MATTER_FRAGMENT = REGISTRY.register("perfect_matter_fragment", PerfectMatterFragmentItem::new);
	public static final DeferredItem<Item> PERFECT_MATTER_BLOCK = block(ExtremeMonstersModBlocks.PERFECT_MATTER_BLOCK);
	public static final DeferredItem<Item> INFINITY_MATRIX = block(ExtremeMonstersModBlocks.INFINITY_MATRIX);
	public static final DeferredItem<Item> INFINITY_SIMULATION_CHAMBER = block(ExtremeMonstersModBlocks.INFINITY_SIMULATION_CHAMBER);
	public static final DeferredItem<Item> ULTIMATE_SOUL = REGISTRY.register("ultimate_soul", UltimateSoulItem::new);
	public static final DeferredItem<Item> WITHER_INCUBATOR = block(ExtremeMonstersModBlocks.WITHER_INCUBATOR);
	public static final DeferredItem<Item> WITHER_IN_THE_BOTTLE = REGISTRY.register("wither_in_the_bottle", WitherInTheBottleItem::new);
	public static final DeferredItem<Item> HYPER_WITHER_IN_THE_BOTTLE = REGISTRY.register("hyper_wither_in_the_bottle", HyperWitherInTheBottleItem::new);
	public static final DeferredItem<Item> PERFECT_MATTER_HAMMER = REGISTRY.register("perfect_matter_hammer", PerfectMatterHammerItem::new);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_HAMMER = REGISTRY.register("black_hole_matter_hammer", BlackHoleMatterHammerItem::new);
	public static final DeferredItem<Item> DARK_MATTER_HAMMER = REGISTRY.register("dark_matter_hammer", DarkMatterHammerItem::new);
	public static final DeferredItem<Item> INFERNO_MATTER_HAMMER = REGISTRY.register("inferno_matter_hammer", InfernoMatterHammerItem::new);
	public static final DeferredItem<Item> DRAGON_MATTER_HAMMER = REGISTRY.register("dragon_matter_hammer", DragonMatterHammerItem::new);
	public static final DeferredItem<Item> WITHER_MATTER_HAMMER = REGISTRY.register("wither_matter_hammer", WitherMatterHammerItem::new);
	public static final DeferredItem<Item> DARK_MATTER_GENERATOR_MK_4 = block(ExtremeMonstersModBlocks.DARK_MATTER_GENERATOR_MK_4);
	public static final DeferredItem<Item> INFINITE_WATER_SOURCE = block(ExtremeMonstersModBlocks.INFINITE_WATER_SOURCE);
	public static final DeferredItem<Item> INFINITE_LAVA_SOURCE = block(ExtremeMonstersModBlocks.INFINITE_LAVA_SOURCE);
	public static final DeferredItem<Item> DARK_MATTER_GENERATOR_MK_5 = block(ExtremeMonstersModBlocks.DARK_MATTER_GENERATOR_MK_5);
	public static final DeferredItem<Item> COPPER_GENERATOR = block(ExtremeMonstersModBlocks.COPPER_GENERATOR);
	public static final DeferredItem<Item> APPLE_CULTIVATOR_MK_1 = block(ExtremeMonstersModBlocks.APPLE_CULTIVATOR_MK_1);
	public static final DeferredItem<Item> APPLE_CULTIVATOR_MK_2 = block(ExtremeMonstersModBlocks.APPLE_CULTIVATOR_MK_2);
	public static final DeferredItem<Item> MATTER_CATALYST_COMPRESSOR_1 = block(ExtremeMonstersModBlocks.MATTER_CATALYST_COMPRESSOR_1);
	public static final DeferredItem<Item> MATTER_CATALYST_COMPRESSOR_2 = block(ExtremeMonstersModBlocks.MATTER_CATALYST_COMPRESSOR_2);
	public static final DeferredItem<Item> MATTER_CATALYST_COMPRESSOR_3 = block(ExtremeMonstersModBlocks.MATTER_CATALYST_COMPRESSOR_3);
	public static final DeferredItem<Item> ASSEMBLER_UPGRADE_1 = REGISTRY.register("assembler_upgrade_1", AssemblerUpgrade1Item::new);
	public static final DeferredItem<Item> ASSEMBLER_UPGRADE_2 = REGISTRY.register("assembler_upgrade_2", AssemblerUpgrade2Item::new);
	public static final DeferredItem<Item> ASSEMBLER_UPGRADE_3 = REGISTRY.register("assembler_upgrade_3", AssemblerUpgrade3Item::new);
	public static final DeferredItem<Item> DUPLICATED_SOUL = REGISTRY.register("duplicated_soul", DuplicatedSoulItem::new);
	public static final DeferredItem<Item> DUPLICATED_NETHER_STAR = REGISTRY.register("duplicated_nether_star", DuplicatedNetherStarItem::new);
	public static final DeferredItem<Item> SOUL_ESSENCE = REGISTRY.register("soul_essence", SoulEssenceItem::new);
	public static final DeferredItem<Item> IRON_GENERATOR = block(ExtremeMonstersModBlocks.IRON_GENERATOR);
	public static final DeferredItem<Item> REDSTONE_GENERATOR = block(ExtremeMonstersModBlocks.REDSTONE_GENERATOR);
	public static final DeferredItem<Item> DUPLICATED_LEATHER = REGISTRY.register("duplicated_leather", DuplicatedLeatherItem::new);
	public static final DeferredItem<Item> ULTIMATE_INGOT = REGISTRY.register("ultimate_ingot", UltimateIngotItem::new);
	public static final DeferredItem<Item> ULTIMATE_BLOCK = block(ExtremeMonstersModBlocks.ULTIMATE_BLOCK);
	public static final DeferredItem<Item> ZIO_INSERTER = block(ExtremeMonstersModBlocks.ZIO_INSERTER);
	public static final DeferredItem<Item> ZIO_WRENCH = REGISTRY.register("zio_wrench", ZioWrenchItem::new);
	public static final DeferredItem<Item> ZIO_EXPORTER = block(ExtremeMonstersModBlocks.ZIO_EXPORTER);
	public static final DeferredItem<Item> DARK_MATTER_QUANTUM_VAULT = block(ExtremeMonstersModBlocks.DARK_MATTER_QUANTUM_VAULT);
	public static final DeferredItem<Item> QUANTUM_ENTANGLER = REGISTRY.register("quantum_entangler", QuantumEntanglerItem::new);
	public static final DeferredItem<Item> INFINITE_COBBLESTONE_SOURCE = block(ExtremeMonstersModBlocks.INFINITE_COBBLESTONE_SOURCE);
	public static final DeferredItem<Item> EMPTY_ITEM_SLOT = REGISTRY.register("empty_item_slot", EmptyItemSlotItem::new);
	public static final DeferredItem<Item> DISPOSABLE_HYPER_MOB_DESIGNATOR = REGISTRY.register("disposable_hyper_mob_designator", DisposableHyperMobDesignatorItem::new);
	public static final DeferredItem<Item> NORMAL_ARROW = REGISTRY.register("normal_arrow", NormalArrowItem::new);
	public static final DeferredItem<Item> FICTIONAL_PLANET = REGISTRY.register(ExtremeMonstersModBlocks.FICTIONAL_PLANET.getId().getPath(),
			() -> new FictionalPlanetDisplayItem(ExtremeMonstersModBlocks.FICTIONAL_PLANET.get(), new Item.Properties()));
	public static final DeferredItem<Item> INFERNO_ENERGY_ACCEPTOR = block(ExtremeMonstersModBlocks.INFERNO_ENERGY_ACCEPTOR);
	public static final DeferredItem<Item> INFERNO_MINING_CONTROLLER = block(ExtremeMonstersModBlocks.INFERNO_MINING_CONTROLLER);
	public static final DeferredItem<Item> INFERNO_ITEM_OUTPUT_BLOCK = block(ExtremeMonstersModBlocks.INFERNO_ITEM_OUTPUT_BLOCK);
	public static final DeferredItem<Item> INFERNO_MINING_CASING = block(ExtremeMonstersModBlocks.INFERNO_MINING_CASING);
	public static final DeferredItem<Item> INFERNO_QUANTUM_DRILL = block(ExtremeMonstersModBlocks.INFERNO_QUANTUM_DRILL);
	public static final DeferredItem<Item> SMELTING_UPGRADE = REGISTRY.register("smelting_upgrade", SmeltingUpgradeItem::new);
	public static final DeferredItem<Item> FICTIONAL_PLANET_MODEL = REGISTRY.register("fictional_planet_model", FictionalPlanetModelItem::new);
	public static final DeferredItem<Item> INFERNO_FICTIONAL_PLANET_MODEL_MODIFIER = block(ExtremeMonstersModBlocks.INFERNO_FICTIONAL_PLANET_MODEL_MODIFIER);
	public static final DeferredItem<Item> RAW_TUNGSTEN = REGISTRY.register("raw_tungsten", RawTungstenItem::new);
	public static final DeferredItem<Item> TUNGSTEN_INGOT = REGISTRY.register("tungsten_ingot", TungstenIngotItem::new);
	public static final DeferredItem<Item> RAW_TUNGSTEN_BLOCK = block(ExtremeMonstersModBlocks.RAW_TUNGSTEN_BLOCK);
	public static final DeferredItem<Item> TUNGSTEN_BLOCK = block(ExtremeMonstersModBlocks.TUNGSTEN_BLOCK);
	public static final DeferredItem<Item> DRAGON_MATTER_FUEL = REGISTRY.register("dragon_matter_fuel", DragonMatterFuelItem::new);
	public static final DeferredItem<Item> WITHER_MATTER_FUEL = REGISTRY.register("wither_matter_fuel", WitherMatterFuelItem::new);
	public static final DeferredItem<Item> ARTIFICIAL_SUN = REGISTRY.register(ExtremeMonstersModBlocks.ARTIFICIAL_SUN.getId().getPath(), () -> new ArtificialSunDisplayItem(ExtremeMonstersModBlocks.ARTIFICIAL_SUN.get(), new Item.Properties()));
	public static final DeferredItem<Item> PLANETARY_REGULATOR = REGISTRY.register(ExtremeMonstersModBlocks.PLANETARY_REGULATOR.getId().getPath(),
			() -> new PlanetaryRegulatorDisplayItem(ExtremeMonstersModBlocks.PLANETARY_REGULATOR.get(), new Item.Properties()));
	public static final DeferredItem<Item> DRAGON_MINING_CONTROLLER = block(ExtremeMonstersModBlocks.DRAGON_MINING_CONTROLLER);
	public static final DeferredItem<Item> DRAGON_ENERGY_ACCEPTOR = block(ExtremeMonstersModBlocks.DRAGON_ENERGY_ACCEPTOR);
	public static final DeferredItem<Item> DRAGON_MINING_CASING = block(ExtremeMonstersModBlocks.DRAGON_MINING_CASING);
	public static final DeferredItem<Item> DRAGON_QUANTUM_DRILL = block(ExtremeMonstersModBlocks.DRAGON_QUANTUM_DRILL);
	public static final DeferredItem<Item> DRAGON_ITEM_OUTPUT_BLOCK = block(ExtremeMonstersModBlocks.DRAGON_ITEM_OUTPUT_BLOCK);
	public static final DeferredItem<Item> TUNGSTEN_BAT = REGISTRY.register("tungsten_bat", TungstenBatItem::new);
	public static final DeferredItem<Item> QUANTUM_ANCHOR = block(ExtremeMonstersModBlocks.QUANTUM_ANCHOR);
	public static final DeferredItem<Item> DARK_MATTER_BOILER_CASING = block(ExtremeMonstersModBlocks.DARK_MATTER_BOILER_CASING);
	public static final DeferredItem<Item> DARK_MATTER_HEAT_CONDUCTION_COIL = block(ExtremeMonstersModBlocks.DARK_MATTER_HEAT_CONDUCTION_COIL);
	public static final DeferredItem<Item> DARK_FLUID_INPUT_BLOCK = block(ExtremeMonstersModBlocks.DARK_FLUID_INPUT_BLOCK);
	public static final DeferredItem<Item> DARK_ITEM_OUTPUT_BLOCK = block(ExtremeMonstersModBlocks.DARK_ITEM_OUTPUT_BLOCK);
	public static final DeferredItem<Item> MATTER_CATALYST_BOILER_CONTROLLER = block(ExtremeMonstersModBlocks.MATTER_CATALYST_BOILER_CONTROLLER);
	public static final DeferredItem<Item> DARK_MATTER_GROWTH_ACCELERATOR = block(ExtremeMonstersModBlocks.DARK_MATTER_GROWTH_ACCELERATOR);
	public static final DeferredItem<Item> PERFECT_ABYSS = REGISTRY.register("perfect_abyss", PerfectAbyssItem::new);
	public static final DeferredItem<Item> INFINITY_TRACKER_DEFENDER = block(ExtremeMonstersModBlocks.INFINITY_TRACKER_DEFENDER);
	public static final DeferredItem<Item> SUPER_SMELTING_BLOCK = block(ExtremeMonstersModBlocks.SUPER_SMELTING_BLOCK);
	public static final DeferredItem<Item> DRAGON_QSS_CONTROLLER = block(ExtremeMonstersModBlocks.DRAGON_QSS_CONTROLLER);
	public static final DeferredItem<Item> DRAGON_QSS_CASING = block(ExtremeMonstersModBlocks.DRAGON_QSS_CASING);
	public static final DeferredItem<Item> DRAGON_QSS_STABILIZER = block(ExtremeMonstersModBlocks.DRAGON_QSS_STABILIZER);
	public static final DeferredItem<Item> DRAGON_QSS_QUBIT_MEMORY = block(ExtremeMonstersModBlocks.DRAGON_QSS_QUBIT_MEMORY);
	public static final DeferredItem<Item> DRAGON_QSS_ERROR_SOLVER = block(ExtremeMonstersModBlocks.DRAGON_QSS_ERROR_SOLVER);
	public static final DeferredItem<Item> DRAGON_QSS_OUTPUT_BLOCK = block(ExtremeMonstersModBlocks.DRAGON_QSS_OUTPUT_BLOCK);
	public static final DeferredItem<Item> USABLE_STARS_SOUL = REGISTRY.register("usable_stars_soul", UsableStarsSoulItem::new);
	public static final DeferredItem<Item> REINFORCED_REDSTONE_BLOCK = block(ExtremeMonstersModBlocks.REINFORCED_REDSTONE_BLOCK);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_CRYSTAL_MATRIX_INGOT = REGISTRY.register("black_hole_matter_crystal_matrix_ingot", BlackHoleMatterCrystalMatrixIngotItem::new);
	public static final DeferredItem<Item> DARK_MATTER_CRYSTAL_MATRIX_INGOT = REGISTRY.register("dark_matter_crystal_matrix_ingot", DarkMatterCrystalMatrixIngotItem::new);
	public static final DeferredItem<Item> INFERNO_MATTER_CRYSTAL_MATRIX_INGOT = REGISTRY.register("inferno_matter_crystal_matrix_ingot", InfernoMatterCrystalMatrixIngotItem::new);
	public static final DeferredItem<Item> DRAGON_MATTER_CRYSTAL_MATRIX_INGOT = REGISTRY.register("dragon_matter_crystal_matrix_ingot", DragonMatterCrystalMatrixIngotItem::new);
	public static final DeferredItem<Item> WITHER_MATTER_CRYSTAL_MATRIX_INGOT = REGISTRY.register("wither_matter_crystal_matrix_ingot", WitherMatterCrystalMatrixIngotItem::new);
	public static final DeferredItem<Item> TEAR_EXTRACTOR_MK_1 = block(ExtremeMonstersModBlocks.TEAR_EXTRACTOR_MK_1);
	public static final DeferredItem<Item> NETHER_STAR_BLOCK = block(ExtremeMonstersModBlocks.NETHER_STAR_BLOCK);
	public static final DeferredItem<Item> TUNGSTEN_CRYSTAL_MATRIX_INGOT = REGISTRY.register("tungsten_crystal_matrix_ingot", TungstenCrystalMatrixIngotItem::new);
	public static final DeferredItem<Item> TUNGSTEN_CRYSTAL_MATRIX_BLOCK = block(ExtremeMonstersModBlocks.TUNGSTEN_CRYSTAL_MATRIX_BLOCK);
	public static final DeferredItem<Item> POS_TELEPORTER = REGISTRY.register("pos_teleporter", PosTeleporterItem::new);
	public static final DeferredItem<Item> SUPER_TRACKER_SPAWN_EGG = REGISTRY.register("super_tracker_spawn_egg", () -> new DeferredSpawnEggItem(ExtremeMonstersModEntities.SUPER_TRACKER, -13421773, -16777216, new Item.Properties()));
	public static final DeferredItem<Item> SUPER_TRACKER_PAGER = REGISTRY.register("super_tracker_pager", SuperTrackerPagerItem::new);
	public static final DeferredItem<Item> WITHER_MACHINE_FRAME = block(ExtremeMonstersModBlocks.WITHER_MACHINE_FRAME);
	public static final DeferredItem<Item> INFERNO_MATTER_ASSEMBLER = block(ExtremeMonstersModBlocks.INFERNO_MATTER_ASSEMBLER);
	public static final DeferredItem<Item> MIXED_HYPER_ESSENCE = REGISTRY.register("mixed_hyper_essence", MixedHyperEssenceItem::new);
	public static final DeferredItem<Item> MIXED_HYPER_INGOT = REGISTRY.register("mixed_hyper_ingot", MixedHyperIngotItem::new);
	public static final DeferredItem<Item> KILLMKILL_97_BLOCK = block(ExtremeMonstersModBlocks.KILLMKILL_97_BLOCK);
	public static final DeferredItem<Item> TUNGSTEN_FURNACE = block(ExtremeMonstersModBlocks.TUNGSTEN_FURNACE);
	public static final DeferredItem<Item> DUPLICATOR_MK_2 = block(ExtremeMonstersModBlocks.DUPLICATOR_MK_2);
	public static final DeferredItem<Item> HYPER_ENDER_WITHER_IN_THE_BOTTLE = REGISTRY.register("hyper_ender_wither_in_the_bottle", HyperEnderWitherInTheBottleItem::new);
	public static final DeferredItem<Item> SUPER_LAVA_BUCKET = REGISTRY.register("super_lava_bucket", SuperLavaItem::new);
	public static final DeferredItem<Item> MYSTERY_CUBE = block(ExtremeMonstersModBlocks.MYSTERY_CUBE);
	public static final DeferredItem<Item> HYPER_STONE = block(ExtremeMonstersModBlocks.HYPER_STONE);
	public static final DeferredItem<Item> HYPER_STONE_DESTROYER = REGISTRY.register("hyper_stone_destroyer", HyperStoneDestroyerItem::new);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_STICK = REGISTRY.register("black_hole_matter_stick", BlackHoleMatterStickItem::new);
	public static final DeferredItem<Item> WITHERED_DARK_MATTER_LAUNCHER = REGISTRY.register("withered_dark_matter_launcher", WitheredDarkMatterLauncherItem::new);
	public static final DeferredItem<Item> PERFECT_DARK_MATTER_BARRAGER = REGISTRY.register("perfect_dark_matter_barrager", PerfectDarkMatterBarragerItem::new);
	public static final DeferredItem<Item> HYPER_NETHER_BRICKS = block(ExtremeMonstersModBlocks.HYPER_NETHER_BRICKS);
	public static final DeferredItem<Item> HYPER_GOLDEN_AXE = REGISTRY.register("hyper_golden_axe", HyperGoldenAxeItem::new);
	public static final DeferredItem<Item> VAPOR_EMITTER = REGISTRY.register("vapor_emitter", VaporEmitterItem::new);
	public static final DeferredItem<Item> HYPER_ITEM_MAGNET = REGISTRY.register("hyper_item_magnet", HyperItemMagnetItem::new);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_LASER_EMITTER = REGISTRY.register("black_hole_matter_laser_emitter", BlackHoleMatterLaserEmitterItem::new);
	public static final DeferredItem<Item> STASIS_LASER_EMITTER = REGISTRY.register("stasis_laser_emitter", StasisLaserEmitterItem::new);
	public static final DeferredItem<Item> INFERNO_RAIL_GUN_STICK = REGISTRY.register("inferno_rail_gun_stick", InfernoRailGunStickItem::new);
	public static final DeferredItem<Item> INFERNO_RAIL_GUN = REGISTRY.register("inferno_rail_gun", InfernoRailGunItem::new);
	public static final DeferredItem<Item> MATTER_CATALYST_INGOT = REGISTRY.register("matter_catalyst_ingot", MatterCatalystIngotItem::new);
	public static final DeferredItem<Item> SUPER_MATTER_CATALYST = REGISTRY.register("super_matter_catalyst", SuperMatterCatalystItem::new);
	public static final DeferredItem<Item> STASIS_RAIL_GUN = REGISTRY.register("stasis_rail_gun", StasisRailGunItem::new);
	public static final DeferredItem<Item> STASIS_RAIL_GUN_STICK = REGISTRY.register("stasis_rail_gun_stick", StasisRailGunStickItem::new);
	public static final DeferredItem<Item> END_MYSTERY_CUBE = block(ExtremeMonstersModBlocks.END_MYSTERY_CUBE);
	public static final DeferredItem<Item> HYPER_TOTEM_OF_UNDYING = REGISTRY.register("hyper_totem_of_undying", HyperTotemOfUndyingItem::new);
	public static final DeferredItem<Item> ASCENDED_EVASION_AMULET = REGISTRY.register("ascended_evasion_amulet", AscendedEvasionAmuletItem::new);
	public static final DeferredItem<Item> BLACK_HOLE_MATTER_SAPLING = block(ExtremeMonstersModBlocks.BLACK_HOLE_MATTER_SAPLING);
	public static final DeferredItem<Item> DARK_MATTER_SAPLING = block(ExtremeMonstersModBlocks.DARK_MATTER_SAPLING);
	public static final DeferredItem<Item> INFERNO_MATTER_SAPLING = block(ExtremeMonstersModBlocks.INFERNO_MATTER_SAPLING);
	public static final DeferredItem<Item> HYPER_TRACKER_SPAWN_EGG = REGISTRY.register("hyper_tracker_spawn_egg", () -> new DeferredSpawnEggItem(ExtremeMonstersModEntities.HYPER_TRACKER, -13421773, -10066330, new Item.Properties()));
	public static final DeferredItem<Item> TRACKER_CORE = REGISTRY.register("tracker_core", TrackerCoreItem::new);
	public static final DeferredItem<Item> HYPER_TRACKER_PAGER = REGISTRY.register("hyper_tracker_pager", HyperTrackerPagerItem::new);
	public static final DeferredItem<Item> TRACKER_IN_THE_BOTTLE = REGISTRY.register("tracker_in_the_bottle", TrackerInTheBottleItem::new);
	public static final DeferredItem<Item> HYPER_TRACKER_IN_THE_BOTTLE = REGISTRY.register("hyper_tracker_in_the_bottle", HyperTrackerInTheBottleItem::new);
	public static final DeferredItem<Item> TRACKER_INCUBATOR = block(ExtremeMonstersModBlocks.TRACKER_INCUBATOR);
	public static final DeferredItem<Item> GOLDEN_SAPLING = block(ExtremeMonstersModBlocks.GOLDEN_SAPLING);
	public static final DeferredItem<Item> DRAGON_MATTER_APPLE = REGISTRY.register("dragon_matter_apple", DragonMatterAppleItem::new);
	public static final DeferredItem<Item> WITHER_MATTER_APPLE = REGISTRY.register("wither_matter_apple", WitherMatterAppleItem::new);
	public static final DeferredItem<Item> TAMABLE_TRACKER_SPAWN_EGG = REGISTRY.register("tamable_tracker_spawn_egg", () -> new DeferredSpawnEggItem(ExtremeMonstersModEntities.TAMABLE_TRACKER, -13421773, -14671840, new Item.Properties()));
	public static final DeferredItem<Item> CONTAINED_SUPER_TRACKER = REGISTRY.register(ExtremeMonstersModBlocks.CONTAINED_SUPER_TRACKER.getId().getPath(),
			() -> new ContainedSuperTrackerDisplayItem(ExtremeMonstersModBlocks.CONTAINED_SUPER_TRACKER.get(), new Item.Properties()));
	public static final DeferredItem<Item> TRACKER_CONTAINMENT_CAGE = REGISTRY.register(ExtremeMonstersModBlocks.TRACKER_CONTAINMENT_CAGE.getId().getPath(),
			() -> new TrackerContainmentCageDisplayItem(ExtremeMonstersModBlocks.TRACKER_CONTAINMENT_CAGE.get(), new Item.Properties()));
	public static final DeferredItem<Item> TAMABLE_TRACKER_CUBE = block(ExtremeMonstersModBlocks.TAMABLE_TRACKER_CUBE);
	public static final DeferredItem<Item> ULTIMATE_CORE = REGISTRY.register("ultimate_core", UltimateCoreItem::new);
	public static final DeferredItem<Item> SUPER_DAMAGE_PROTECTOR = REGISTRY.register("super_damage_protector", SuperDamageProtectorItem::new);
	public static final DeferredItem<Item> INFERNO_MATTER_BAND_AID = REGISTRY.register("inferno_matter_band_aid", InfernoMatterBandAidItem::new);
	public static final DeferredItem<Item> DRAGON_MATTER_BAND_AID = REGISTRY.register("dragon_matter_band_aid", DragonMatterBandAidItem::new);
	public static final DeferredItem<Item> WITHER_MATTER_BAND_AID = REGISTRY.register("wither_matter_band_aid", WitherMatterBandAidItem::new);
	public static final DeferredItem<Item> WEAK_TRACKER_SPAWN_EGG = REGISTRY.register("weak_tracker_spawn_egg", () -> new DeferredSpawnEggItem(ExtremeMonstersModEntities.WEAK_TRACKER, -10066330, -13421773, new Item.Properties()));
	public static final DeferredItem<Item> WEAK_FLYING_TRACKER_SPAWN_EGG = REGISTRY.register("weak_flying_tracker_spawn_egg",
			() -> new DeferredSpawnEggItem(ExtremeMonstersModEntities.WEAK_FLYING_TRACKER, -10066330, -13421773, new Item.Properties()));
	public static final DeferredItem<Item> COMBINED_PASS = REGISTRY.register("combined_pass", CombinedPassItem::new);
	public static final DeferredItem<Item> ARTIFICIAL_NEUTRON_STAR = REGISTRY.register(ExtremeMonstersModBlocks.ARTIFICIAL_NEUTRON_STAR.getId().getPath(),
			() -> new ArtificialNeutronStarDisplayItem(ExtremeMonstersModBlocks.ARTIFICIAL_NEUTRON_STAR.get(), new Item.Properties()));
	public static final DeferredItem<Item> AMMO_EXTRACTOR = REGISTRY.register("ammo_extractor", AmmoExtractorItem::new);
	public static final DeferredItem<Item> CONDENSED_SOLAR_RESIDUUM = REGISTRY.register("condensed_solar_residuum", CondensedSolarResiduumItem::new);
	public static final DeferredItem<Item> SOLAR_RESIDUUM_COLLECTOR = block(ExtremeMonstersModBlocks.SOLAR_RESIDUUM_COLLECTOR);
	public static final DeferredItem<Item> HFE_UP_SCALER = block(ExtremeMonstersModBlocks.HFE_UP_SCALER);
	public static final DeferredItem<Item> WITHER_HFE_CUBE = block(ExtremeMonstersModBlocks.WITHER_HFE_CUBE);
	public static final DeferredItem<Item> HFE_DOWN_SCALER = block(ExtremeMonstersModBlocks.HFE_DOWN_SCALER);
	public static final DeferredItem<Item> CREATIVE_HFE_GENERATOR = block(ExtremeMonstersModBlocks.CREATIVE_HFE_GENERATOR);
	public static final DeferredItem<Item> WITHER_MATTER_HFE_RELAY = block(ExtremeMonstersModBlocks.WITHER_MATTER_HFE_RELAY);
	public static final DeferredItem<Item> DYSON_RING_CONTROLLER = block(ExtremeMonstersModBlocks.DYSON_RING_CONTROLLER);
	public static final DeferredItem<Item> DYSON_RING_SOLAR_PANEL = block(ExtremeMonstersModBlocks.DYSON_RING_SOLAR_PANEL);
	public static final DeferredItem<Item> QUANTUM_IGNITER = block(ExtremeMonstersModBlocks.QUANTUM_IGNITER);
	public static final DeferredItem<Item> PERFECT_HFE_CUBE = block(ExtremeMonstersModBlocks.PERFECT_HFE_CUBE);
	public static final DeferredItem<Item> MOLECULAR_ASSEMBLER = block(ExtremeMonstersModBlocks.MOLECULAR_ASSEMBLER);
	public static final DeferredItem<Item> MOLECULAR_SOLVENT_BUCKET = REGISTRY.register("molecular_solvent_bucket", MolecularSolventItem::new);
	public static final DeferredItem<Item> MOLECULAR_DISSOLVER = block(ExtremeMonstersModBlocks.MOLECULAR_DISSOLVER);
	public static final DeferredItem<Item> SUPERCHARGED_DARK_MATTER = REGISTRY.register("supercharged_dark_matter", SuperchargedDarkMatterItem::new);
	public static final DeferredItem<Item> MOLECULAR_MATTER_RESYNTHESIZER = block(ExtremeMonstersModBlocks.MOLECULAR_MATTER_RESYNTHESIZER);
	public static final DeferredItem<Item> MOLECULAR_ALLOY_INGOT = REGISTRY.register("molecular_alloy_ingot", MolecularAlloyIngotItem::new);
	public static final DeferredItem<Item> MOLECULAR_ALLOYING_FORGE = block(ExtremeMonstersModBlocks.MOLECULAR_ALLOYING_FORGE);
	public static final DeferredItem<Item> QUASAR = REGISTRY.register("quasar", QuasarItem::new);
	public static final DeferredItem<Item> MOLECULAR_COMPRESSION_STATION = block(ExtremeMonstersModBlocks.MOLECULAR_COMPRESSION_STATION);
	public static final DeferredItem<Item> DENSE_IRON_INGOT_1 = REGISTRY.register("dense_iron_ingot_1", DenseIronIngot1Item::new);
	public static final DeferredItem<Item> DENSE_IRON_INGOT_2 = REGISTRY.register("dense_iron_ingot_2", DenseIronIngot2Item::new);
	public static final DeferredItem<Item> DENSE_IRON_INGOT_3 = REGISTRY.register("dense_iron_ingot_3", DenseIronIngot3Item::new);
	public static final DeferredItem<Item> DENSE_IRON_INGOT_4 = REGISTRY.register("dense_iron_ingot_4", DenseIronIngot4Item::new);
	public static final DeferredItem<Item> DENSE_IRON_INGOT_5 = REGISTRY.register("dense_iron_ingot_5", DenseIronIngot5Item::new);
	public static final DeferredItem<Item> COLLAPSED_IRON_INGOT = REGISTRY.register("collapsed_iron_ingot", CollapsedIronIngotItem::new);
	public static final DeferredItem<Item> DENSE_GOLD_INGOT_1 = REGISTRY.register("dense_gold_ingot_1", DenseGoldIngot1Item::new);
	public static final DeferredItem<Item> DENSE_GOLD_INGOT_2 = REGISTRY.register("dense_gold_ingot_2", DenseGoldIngot2Item::new);
	public static final DeferredItem<Item> DENSE_GOLD_INGOT_3 = REGISTRY.register("dense_gold_ingot_3", DenseGoldIngot3Item::new);
	public static final DeferredItem<Item> DENSE_GOLD_INGOT_4 = REGISTRY.register("dense_gold_ingot_4", DenseGoldIngot4Item::new);
	public static final DeferredItem<Item> DENSE_GOLD_INGOT_5 = REGISTRY.register("dense_gold_ingot_5", DenseGoldIngot5Item::new);
	public static final DeferredItem<Item> COLLAPSED_GOLD_INGOT = REGISTRY.register("collapsed_gold_ingot", CollapsedGoldIngotItem::new);
	public static final DeferredItem<Item> DENSE_COPPER_INGOT_1 = REGISTRY.register("dense_copper_ingot_1", DenseCopperIngot1Item::new);
	public static final DeferredItem<Item> DENSE_COPPER_INGOT_2 = REGISTRY.register("dense_copper_ingot_2", DenseCopperIngot2Item::new);
	public static final DeferredItem<Item> DENSE_COPPER_INGOT_3 = REGISTRY.register("dense_copper_ingot_3", DenseCopperIngot3Item::new);
	public static final DeferredItem<Item> DENSE_COPPER_INGOT_4 = REGISTRY.register("dense_copper_ingot_4", DenseCopperIngot4Item::new);
	public static final DeferredItem<Item> DENSE_COPPER_INGOT_5 = REGISTRY.register("dense_copper_ingot_5", DenseCopperIngot5Item::new);
	public static final DeferredItem<Item> COLLAPSED_COPPER_INGOT = REGISTRY.register("collapsed_copper_ingot", CollapsedCopperIngotItem::new);
	public static final DeferredItem<Item> DENSE_DIAMOND_1 = REGISTRY.register("dense_diamond_1", DenseDiamond1Item::new);
	public static final DeferredItem<Item> DENSE_DIAMOND_2 = REGISTRY.register("dense_diamond_2", DenseDiamond2Item::new);
	public static final DeferredItem<Item> DENSE_DIAMOND_3 = REGISTRY.register("dense_diamond_3", DenseDiamond3Item::new);
	public static final DeferredItem<Item> DENSE_DIAMOND_4 = REGISTRY.register("dense_diamond_4", DenseDiamond4Item::new);
	public static final DeferredItem<Item> DENSE_DIAMOND_5 = REGISTRY.register("dense_diamond_5", DenseDiamond5Item::new);
	public static final DeferredItem<Item> COLLAPSED_DIAMOND = REGISTRY.register("collapsed_diamond", CollapsedDiamondItem::new);
	public static final DeferredItem<Item> DENSE_REDSTONE_1 = REGISTRY.register("dense_redstone_1", DenseRedstone1Item::new);
	public static final DeferredItem<Item> DENSE_REDSTONE_2 = REGISTRY.register("dense_redstone_2", DenseRedstone2Item::new);
	public static final DeferredItem<Item> DENSE_REDSTONE_3 = REGISTRY.register("dense_redstone_3", DenseRedstone3Item::new);
	public static final DeferredItem<Item> DENSE_REDSTONE_4 = REGISTRY.register("dense_redstone_4", DenseRedstone4Item::new);
	public static final DeferredItem<Item> DENSE_REDSTONE_5 = REGISTRY.register("dense_redstone_5", DenseRedstone5Item::new);
	public static final DeferredItem<Item> COLLAPSED_REDSTONE = REGISTRY.register("collapsed_redstone", CollapsedRedstoneItem::new);
	public static final DeferredItem<Item> DENSE_NETHERITE_INGOT_1 = REGISTRY.register("dense_netherite_ingot_1", DenseNetheriteIngot1Item::new);
	public static final DeferredItem<Item> DENSE_NETHERITE_INGOT_2 = REGISTRY.register("dense_netherite_ingot_2", DenseNetheriteIngot2Item::new);
	public static final DeferredItem<Item> DENSE_NETHERITE_INGOT_3 = REGISTRY.register("dense_netherite_ingot_3", DenseNetheriteIngot3Item::new);
	public static final DeferredItem<Item> DENSE_NETHERITE_INGOT_4 = REGISTRY.register("dense_netherite_ingot_4", DenseNetheriteIngot4Item::new);
	public static final DeferredItem<Item> DENSE_NETHERITE_INGOT_5 = REGISTRY.register("dense_netherite_ingot_5", DenseNetheriteIngot5Item::new);
	public static final DeferredItem<Item> COLLAPSED_NETHERITE_INGOT = REGISTRY.register("collapsed_netherite_ingot", CollapsedNetheriteIngotItem::new);
	public static final DeferredItem<Item> DENSE_COAL_1 = REGISTRY.register("dense_coal_1", DenseCoal1Item::new);
	public static final DeferredItem<Item> DENSE_COAL_2 = REGISTRY.register("dense_coal_2", DenseCoal2Item::new);
	public static final DeferredItem<Item> DENSE_COAL_3 = REGISTRY.register("dense_coal_3", DenseCoal3Item::new);
	public static final DeferredItem<Item> DENSE_COAL_4 = REGISTRY.register("dense_coal_4", DenseCoal4Item::new);
	public static final DeferredItem<Item> DENSE_COAL_5 = REGISTRY.register("dense_coal_5", DenseCoal5Item::new);
	public static final DeferredItem<Item> COLLAPSED_COAL = REGISTRY.register("collapsed_coal", CollapsedCoalItem::new);
	public static final DeferredItem<Item> DENSE_QUARTZ_1 = REGISTRY.register("dense_quartz_1", DenseQuartz1Item::new);
	public static final DeferredItem<Item> DENSE_QUARTZ_2 = REGISTRY.register("dense_quartz_2", DenseQuartz2Item::new);
	public static final DeferredItem<Item> DENSE_QUARTZ_3 = REGISTRY.register("dense_quartz_3", DenseQuartz3Item::new);
	public static final DeferredItem<Item> DENSE_QUARTZ_4 = REGISTRY.register("dense_quartz_4", DenseQuartz4Item::new);
	public static final DeferredItem<Item> DENSE_QUARTZ_5 = REGISTRY.register("dense_quartz_5", DenseQuartz5Item::new);
	public static final DeferredItem<Item> COLLAPSED_QUARTZ = REGISTRY.register("collapsed_quartz", CollapsedQuartzItem::new);
	public static final DeferredItem<Item> MICROVERSE_SIMULATOR_CONTROLLER = block(ExtremeMonstersModBlocks.MICROVERSE_SIMULATOR_CONTROLLER);
	public static final DeferredItem<Item> MICROVERSE_CASING = block(ExtremeMonstersModBlocks.MICROVERSE_CASING);
	public static final DeferredItem<Item> MICROVERSE_ITEM_OUTPUT_BLOCK = block(ExtremeMonstersModBlocks.MICROVERSE_ITEM_OUTPUT_BLOCK);
	public static final DeferredItem<Item> MICROVERSE_INPUT_BLOCK = block(ExtremeMonstersModBlocks.MICROVERSE_INPUT_BLOCK);
	public static final DeferredItem<Item> STELLAR_CATALYST = REGISTRY.register("stellar_catalyst", StellarCatalystItem::new);
	public static final DeferredItem<Item> MICROVERSE_STABILIZER = block(ExtremeMonstersModBlocks.MICROVERSE_STABILIZER);
	public static final DeferredItem<Item> MICROVERSE_SCHEMA = REGISTRY.register("microverse_schema", MicroverseSchemaItem::new);
	public static final DeferredItem<Item> SCHEMA_DIAMOND = REGISTRY.register("schema_diamond", SchemaDiamondItem::new);
	public static final DeferredItem<Item> SCHEMA_IRON = REGISTRY.register("schema_iron", SchemaIronItem::new);
	public static final DeferredItem<Item> SCHEMA_AMETHYST = REGISTRY.register("schema_amethyst", SchemaAmethystItem::new);
	public static final DeferredItem<Item> SCHEMA_GOLD = REGISTRY.register("schema_gold", SchemaGoldItem::new);
	public static final DeferredItem<Item> SCHEMA_COPPER = REGISTRY.register("schema_copper", SchemaCopperItem::new);
	public static final DeferredItem<Item> SCHEMA_QUARTZ = REGISTRY.register("schema_quartz", SchemaQuartzItem::new);
	public static final DeferredItem<Item> SCHEMA_TUNGSTEN = REGISTRY.register("schema_tungsten", SchemaTungstenItem::new);
	public static final DeferredItem<Item> SCHEMA_REDSTONE = REGISTRY.register("schema_redstone", SchemaRedstoneItem::new);
	public static final DeferredItem<Item> SCHEMA_NETHERITE = REGISTRY.register("schema_netherite", SchemaNetheriteItem::new);
	public static final DeferredItem<Item> SCHEMA_STONE = REGISTRY.register("schema_stone", SchemaStoneItem::new);
	public static final DeferredItem<Item> SCHEMA_COAL = REGISTRY.register("schema_coal", SchemaCoalItem::new);
	public static final DeferredItem<Item> MVS_ERA_CHANGER = REGISTRY.register("mvs_era_changer", MVSEraChangerItem::new);
	public static final DeferredItem<Item> SCHEMA_NETHER_STAR = REGISTRY.register("schema_nether_star", SchemaNetherStarItem::new);
	public static final DeferredItem<Item> HYPER_ESSENCE_4 = REGISTRY.register("hyper_essence_4", HyperEssence4Item::new);
	public static final DeferredItem<Item> COMPRESSION_UPGRADE_1 = REGISTRY.register("compression_upgrade_1", CompressionUpgrade1Item::new);
	public static final DeferredItem<Item> COMPRESSION_UPGRADE_2 = REGISTRY.register("compression_upgrade_2", CompressionUpgrade2Item::new);
	public static final DeferredItem<Item> COMPRESSION_UPGRADE_3 = REGISTRY.register("compression_upgrade_3", CompressionUpgrade3Item::new);

	// Start of user code block custom items
	// End of user code block custom items
	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new PosTeleporterInventoryCapability(stack), POS_TELEPORTER.get());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ItemsClientSideHandler {
		@SubscribeEvent
		@OnlyIn(Dist.CLIENT)
		public static void clientLoad(FMLClientSetupEvent event) {
			event.enqueueWork(() -> {
				ItemProperties.register(BLACK_HOLE_MATTER_SHIELD.get(), ResourceLocation.parse("minecraft:blocking"), ItemProperties.getProperty(new ItemStack(Items.SHIELD), ResourceLocation.parse("minecraft:blocking")));
				ItemProperties.register(WITHERED_DARK_MATTER_LAUNCHER.get(), ResourceLocation.parse("extreme_monsters:withered_dark_matter_launcher_griefing"),
						(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) WitheredDarkMatterLauncherTextureChangeProcedure.execute(itemStackToRender));
			});
		}
	}
}
