
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.extrememonsters.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.Block;

import net.mcreator.extrememonsters.block.ZioInserterBlock;
import net.mcreator.extrememonsters.block.ZioExporterBlock;
import net.mcreator.extrememonsters.block.WitherMatterSolarPanelBlock;
import net.mcreator.extrememonsters.block.WitherMatterRelayBlock;
import net.mcreator.extrememonsters.block.WitherMatterIngotBlockBlock;
import net.mcreator.extrememonsters.block.WitherMatterHFERelayBlock;
import net.mcreator.extrememonsters.block.WitherMatterBlockBlock;
import net.mcreator.extrememonsters.block.WitherMachineFrameBlock;
import net.mcreator.extrememonsters.block.WitherIncubatorBlock;
import net.mcreator.extrememonsters.block.WitherHfeCubeBlock;
import net.mcreator.extrememonsters.block.WitherEnergyCubeBlock;
import net.mcreator.extrememonsters.block.WirelessAutoMenderBlock;
import net.mcreator.extrememonsters.block.UltimateBlockBlock;
import net.mcreator.extrememonsters.block.TungstenFurnaceBlock;
import net.mcreator.extrememonsters.block.TungstenCrystalMatrixBlockBlock;
import net.mcreator.extrememonsters.block.TungstenBlockBlock;
import net.mcreator.extrememonsters.block.TrackerIncubatorBlock;
import net.mcreator.extrememonsters.block.TrackerDefenderMk5Block;
import net.mcreator.extrememonsters.block.TrackerDefenderMk4Block;
import net.mcreator.extrememonsters.block.TrackerDefenderMk3Block;
import net.mcreator.extrememonsters.block.TrackerDefenderMk2Block;
import net.mcreator.extrememonsters.block.TrackerDefenderBlock;
import net.mcreator.extrememonsters.block.TrackerContainmentCageBlock;
import net.mcreator.extrememonsters.block.TearExtractorMk1Block;
import net.mcreator.extrememonsters.block.TamableTrackerCubeBlock;
import net.mcreator.extrememonsters.block.SuperSmeltingBlockBlock;
import net.mcreator.extrememonsters.block.SuperMagmaBlock;
import net.mcreator.extrememonsters.block.SuperLavaBlock;
import net.mcreator.extrememonsters.block.SpiderEggBlock;
import net.mcreator.extrememonsters.block.SoulInsertMachineMk3Block;
import net.mcreator.extrememonsters.block.SoulInsertMachineMk2Block;
import net.mcreator.extrememonsters.block.SoulInsertMachineBlock;
import net.mcreator.extrememonsters.block.SolarResiduumCollectorBlock;
import net.mcreator.extrememonsters.block.SimulationChamberMk2Block;
import net.mcreator.extrememonsters.block.SimulationChamberMK3Block;
import net.mcreator.extrememonsters.block.SimulationChamberBlock;
import net.mcreator.extrememonsters.block.ReinforcedRedstoneBlockBlock;
import net.mcreator.extrememonsters.block.RedstoneGeneratorBlock;
import net.mcreator.extrememonsters.block.RawTungstenBlockBlock;
import net.mcreator.extrememonsters.block.QuantumInfuserBlock;
import net.mcreator.extrememonsters.block.QuantumIgniterBlock;
import net.mcreator.extrememonsters.block.QuantumAnchorBlock;
import net.mcreator.extrememonsters.block.ProjectileRemoverBlock;
import net.mcreator.extrememonsters.block.PlanetaryRegulatorBlock;
import net.mcreator.extrememonsters.block.PerfectMatterFoundationBlock;
import net.mcreator.extrememonsters.block.PerfectMatterBlockBlock;
import net.mcreator.extrememonsters.block.PerfectHFECubeBlock;
import net.mcreator.extrememonsters.block.OmegaDCoreStabilizerBlock;
import net.mcreator.extrememonsters.block.OmegaDCoreBlock;
import net.mcreator.extrememonsters.block.NetheriteFusionReactorBlock;
import net.mcreator.extrememonsters.block.NetherStarBlockBlock;
import net.mcreator.extrememonsters.block.MysteryCubeBlock;
import net.mcreator.extrememonsters.block.MolecularSolventBlock;
import net.mcreator.extrememonsters.block.MolecularMatterResynthesizerBlock;
import net.mcreator.extrememonsters.block.MolecularDissolverBlock;
import net.mcreator.extrememonsters.block.MolecularCompressionStationBlock;
import net.mcreator.extrememonsters.block.MolecularAssemblerBlock;
import net.mcreator.extrememonsters.block.MolecularAlloyingForgeBlock;
import net.mcreator.extrememonsters.block.MobSeduceBlock;
import net.mcreator.extrememonsters.block.MobAttackerBlock;
import net.mcreator.extrememonsters.block.MicroverseStabilizerBlock;
import net.mcreator.extrememonsters.block.MicroverseSimulatorControllerBlock;
import net.mcreator.extrememonsters.block.MicroverseItemOutputBlockBlock;
import net.mcreator.extrememonsters.block.MicroverseInputBlockBlock;
import net.mcreator.extrememonsters.block.MicroverseCasingBlock;
import net.mcreator.extrememonsters.block.MatterFusionReactor5Block;
import net.mcreator.extrememonsters.block.MatterFusionReactor4Block;
import net.mcreator.extrememonsters.block.MatterFusionReactor3Block;
import net.mcreator.extrememonsters.block.MatterFusionReactor2Block;
import net.mcreator.extrememonsters.block.MatterFusionReactor1Block;
import net.mcreator.extrememonsters.block.MatterCatalystMakerBlock;
import net.mcreator.extrememonsters.block.MatterCatalystFoundationBlock;
import net.mcreator.extrememonsters.block.MatterCatalystFoundation3xBlock;
import net.mcreator.extrememonsters.block.MatterCatalystFoundation2xBlock;
import net.mcreator.extrememonsters.block.MatterCatalystFoundation1xBlock;
import net.mcreator.extrememonsters.block.MatterCatalystCompressor3Block;
import net.mcreator.extrememonsters.block.MatterCatalystCompressor2Block;
import net.mcreator.extrememonsters.block.MatterCatalystCompressor1Block;
import net.mcreator.extrememonsters.block.MatterCatalystBoilerControllerBlock;
import net.mcreator.extrememonsters.block.Killmkill97BlockBlock;
import net.mcreator.extrememonsters.block.IronGeneratorBlock;
import net.mcreator.extrememonsters.block.InfinityTrackerDefenderBlock;
import net.mcreator.extrememonsters.block.InfinitySimulationChamberBlock;
import net.mcreator.extrememonsters.block.InfinityMatrixBlock;
import net.mcreator.extrememonsters.block.InfiniteWaterSourceBlock;
import net.mcreator.extrememonsters.block.InfiniteLavaSourceBlock;
import net.mcreator.extrememonsters.block.InfiniteCobblestoneSourceBlock;
import net.mcreator.extrememonsters.block.InfernoQuantumDrillBlock;
import net.mcreator.extrememonsters.block.InfernoMiningControllerBlock;
import net.mcreator.extrememonsters.block.InfernoMiningCasingBlock;
import net.mcreator.extrememonsters.block.InfernoMatterSolarPanelBlock;
import net.mcreator.extrememonsters.block.InfernoMatterSaplingBlock;
import net.mcreator.extrememonsters.block.InfernoMatterRelayBlock;
import net.mcreator.extrememonsters.block.InfernoMatterIngotBlockBlock;
import net.mcreator.extrememonsters.block.InfernoMatterBlockBlock;
import net.mcreator.extrememonsters.block.InfernoMatterAssemblerBlock;
import net.mcreator.extrememonsters.block.InfernoItemOutputBlockBlock;
import net.mcreator.extrememonsters.block.InfernoFictionalPlanetModelModifierBlock;
import net.mcreator.extrememonsters.block.InfernoEnergyCubeBlock;
import net.mcreator.extrememonsters.block.InfernoEnergyAcceptorBlock;
import net.mcreator.extrememonsters.block.IceMakerBlock;
import net.mcreator.extrememonsters.block.HyperStoneBlock;
import net.mcreator.extrememonsters.block.HyperNetherBricksBlock;
import net.mcreator.extrememonsters.block.HyperGoldIngotBlockBlock;
import net.mcreator.extrememonsters.block.HfeDownScalerBlock;
import net.mcreator.extrememonsters.block.HFEUpScalerBlock;
import net.mcreator.extrememonsters.block.GoldenSaplingBlock;
import net.mcreator.extrememonsters.block.ForceEmitterBlock;
import net.mcreator.extrememonsters.block.FictionalPlanetBlock;
import net.mcreator.extrememonsters.block.EnergyStabilizerBlock;
import net.mcreator.extrememonsters.block.EndMysteryCubeBlock;
import net.mcreator.extrememonsters.block.DysonRingSolarPanelBlock;
import net.mcreator.extrememonsters.block.DysonRingControllerBlock;
import net.mcreator.extrememonsters.block.DuplicatorMk2Block;
import net.mcreator.extrememonsters.block.DuplicatorBlock;
import net.mcreator.extrememonsters.block.DuplicatedBedrockBlock;
import net.mcreator.extrememonsters.block.DragonQuantumDrillBlock;
import net.mcreator.extrememonsters.block.DragonQssStabilizerBlock;
import net.mcreator.extrememonsters.block.DragonQssQubitMemoryBlock;
import net.mcreator.extrememonsters.block.DragonQssOutputBlockBlock;
import net.mcreator.extrememonsters.block.DragonQssErrorSolverBlock;
import net.mcreator.extrememonsters.block.DragonQssControllerBlock;
import net.mcreator.extrememonsters.block.DragonQssCasingBlock;
import net.mcreator.extrememonsters.block.DragonMiningControllerBlock;
import net.mcreator.extrememonsters.block.DragonMiningCasingBlock;
import net.mcreator.extrememonsters.block.DragonMatterSolarPanelBlock;
import net.mcreator.extrememonsters.block.DragonMatterRelayBlock;
import net.mcreator.extrememonsters.block.DragonMatterIngotBlockBlock;
import net.mcreator.extrememonsters.block.DragonMatterBlockBlock;
import net.mcreator.extrememonsters.block.DragonMachineFrameBlock;
import net.mcreator.extrememonsters.block.DragonItemOutputBlockBlock;
import net.mcreator.extrememonsters.block.DragonIncubatorBlock;
import net.mcreator.extrememonsters.block.DragonEnergyCubeBlock;
import net.mcreator.extrememonsters.block.DragonEnergyAcceptorBlock;
import net.mcreator.extrememonsters.block.DiamondGeneratorBlock;
import net.mcreator.extrememonsters.block.DarkMatterSolarPanelBlock;
import net.mcreator.extrememonsters.block.DarkMatterSaplingBlock;
import net.mcreator.extrememonsters.block.DarkMatterRelayBlock;
import net.mcreator.extrememonsters.block.DarkMatterQuantumVaultBlock;
import net.mcreator.extrememonsters.block.DarkMatterIngotBlockBlock;
import net.mcreator.extrememonsters.block.DarkMatterHeatConductionCoilBlock;
import net.mcreator.extrememonsters.block.DarkMatterGrowthAcceleratorBlock;
import net.mcreator.extrememonsters.block.DarkMatterGeneratorMk5Block;
import net.mcreator.extrememonsters.block.DarkMatterGeneratorMk4Block;
import net.mcreator.extrememonsters.block.DarkMatterGeneratorMk3Block;
import net.mcreator.extrememonsters.block.DarkMatterGeneratorMk2Block;
import net.mcreator.extrememonsters.block.DarkMatterGeneratorBlock;
import net.mcreator.extrememonsters.block.DarkMatterBoilerCasingBlock;
import net.mcreator.extrememonsters.block.DarkMatterBlockBlock;
import net.mcreator.extrememonsters.block.DarkMatterAssemblerBlock;
import net.mcreator.extrememonsters.block.DarkItemOutputBlockBlock;
import net.mcreator.extrememonsters.block.DarkFluidInputBlockBlock;
import net.mcreator.extrememonsters.block.CreativeHFEGeneratorBlock;
import net.mcreator.extrememonsters.block.CreativeGeneratorBlock;
import net.mcreator.extrememonsters.block.CopperGeneratorBlock;
import net.mcreator.extrememonsters.block.ContainedSuperTrackerBlock;
import net.mcreator.extrememonsters.block.CombustionGeneratorMk5Block;
import net.mcreator.extrememonsters.block.CombustionGeneratorMk4Block;
import net.mcreator.extrememonsters.block.CombustionGeneratorMk3Block;
import net.mcreator.extrememonsters.block.CombustionGeneratorMk2Block;
import net.mcreator.extrememonsters.block.CombustionGeneratorBlock;
import net.mcreator.extrememonsters.block.CleverMachineFrameBlock;
import net.mcreator.extrememonsters.block.BlackHoleMatterSolarPlanelBlock;
import net.mcreator.extrememonsters.block.BlackHoleMatterSaplingBlock;
import net.mcreator.extrememonsters.block.BlackHoleMatterRelayBlock;
import net.mcreator.extrememonsters.block.BlackHoleMatterIngotBlockBlock;
import net.mcreator.extrememonsters.block.BlackHoleMatterGlassBlock;
import net.mcreator.extrememonsters.block.BlackHoleMatterBlockBlock;
import net.mcreator.extrememonsters.block.BlackHoleMatterBlock5xBlock;
import net.mcreator.extrememonsters.block.BlackHoleMatterBlock4xBlock;
import net.mcreator.extrememonsters.block.BlackHoleMatterBlock3xBlock;
import net.mcreator.extrememonsters.block.BlackHoleMatterBlock2xBlock;
import net.mcreator.extrememonsters.block.BlackHoleMatterBlock1xBlock;
import net.mcreator.extrememonsters.block.BlackHoleMatterAssemblerBlock;
import net.mcreator.extrememonsters.block.BasicMachineFrameBlock;
import net.mcreator.extrememonsters.block.AwkwardMachineFrameBlock;
import net.mcreator.extrememonsters.block.ArtificialSunBlock;
import net.mcreator.extrememonsters.block.ArtificialNeutronStarBlock;
import net.mcreator.extrememonsters.block.AppleCultivatorMk2Block;
import net.mcreator.extrememonsters.block.AppleCultivatorMk1Block;
import net.mcreator.extrememonsters.block.AlloySmelterBlock;
import net.mcreator.extrememonsters.block.AdvancedMachineFrameBlock;
import net.mcreator.extrememonsters.ExtremeMonstersMod;

public class ExtremeMonstersModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(ExtremeMonstersMod.MODID);
	public static final DeferredBlock<Block> BLACK_HOLE_MATTER_BLOCK = REGISTRY.register("black_hole_matter_block", BlackHoleMatterBlockBlock::new);
	public static final DeferredBlock<Block> BLACK_HOLE_MATTER_GLASS = REGISTRY.register("black_hole_matter_glass", BlackHoleMatterGlassBlock::new);
	public static final DeferredBlock<Block> BLACK_HOLE_MATTER_BLOCK_1X = REGISTRY.register("black_hole_matter_block_1x", BlackHoleMatterBlock1xBlock::new);
	public static final DeferredBlock<Block> BLACK_HOLE_MATTER_BLOCK_2X = REGISTRY.register("black_hole_matter_block_2x", BlackHoleMatterBlock2xBlock::new);
	public static final DeferredBlock<Block> BLACK_HOLE_MATTER_BLOCK_3X = REGISTRY.register("black_hole_matter_block_3x", BlackHoleMatterBlock3xBlock::new);
	public static final DeferredBlock<Block> DARK_MATTER_GENERATOR = REGISTRY.register("dark_matter_generator", DarkMatterGeneratorBlock::new);
	public static final DeferredBlock<Block> BLACK_HOLE_MATTER_SOLAR_PLANEL = REGISTRY.register("black_hole_matter_solar_planel", BlackHoleMatterSolarPlanelBlock::new);
	public static final DeferredBlock<Block> NETHERITE_FUSION_REACTOR = REGISTRY.register("netherite_fusion_reactor", NetheriteFusionReactorBlock::new);
	public static final DeferredBlock<Block> SOUL_INSERT_MACHINE = REGISTRY.register("soul_insert_machine", SoulInsertMachineBlock::new);
	public static final DeferredBlock<Block> SIMULATION_CHAMBER = REGISTRY.register("simulation_chamber", SimulationChamberBlock::new);
	public static final DeferredBlock<Block> BLACK_HOLE_MATTER_ASSEMBLER = REGISTRY.register("black_hole_matter_assembler", BlackHoleMatterAssemblerBlock::new);
	public static final DeferredBlock<Block> AWKWARD_MACHINE_FRAME = REGISTRY.register("awkward_machine_frame", AwkwardMachineFrameBlock::new);
	public static final DeferredBlock<Block> BASIC_MACHINE_FRAME = REGISTRY.register("basic_machine_frame", BasicMachineFrameBlock::new);
	public static final DeferredBlock<Block> MOB_SEDUCE = REGISTRY.register("mob_seduce", MobSeduceBlock::new);
	public static final DeferredBlock<Block> CREATIVE_GENERATOR = REGISTRY.register("creative_generator", CreativeGeneratorBlock::new);
	public static final DeferredBlock<Block> TRACKER_DEFENDER = REGISTRY.register("tracker_defender", TrackerDefenderBlock::new);
	public static final DeferredBlock<Block> BLACK_HOLE_MATTER_RELAY = REGISTRY.register("black_hole_matter_relay", BlackHoleMatterRelayBlock::new);
	public static final DeferredBlock<Block> MATTER_FUSION_REACTOR_1 = REGISTRY.register("matter_fusion_reactor_1", MatterFusionReactor1Block::new);
	public static final DeferredBlock<Block> MATTER_CATALYST_MAKER = REGISTRY.register("matter_catalyst_maker", MatterCatalystMakerBlock::new);
	public static final DeferredBlock<Block> MATTER_CATALYST_FOUNDATION = REGISTRY.register("matter_catalyst_foundation", MatterCatalystFoundationBlock::new);
	public static final DeferredBlock<Block> DARK_MATTER_BLOCK = REGISTRY.register("dark_matter_block", DarkMatterBlockBlock::new);
	public static final DeferredBlock<Block> ADVANCED_MACHINE_FRAME = REGISTRY.register("advanced_machine_frame", AdvancedMachineFrameBlock::new);
	public static final DeferredBlock<Block> TRACKER_DEFENDER_MK_2 = REGISTRY.register("tracker_defender_mk_2", TrackerDefenderMk2Block::new);
	public static final DeferredBlock<Block> DARK_MATTER_RELAY = REGISTRY.register("dark_matter_relay", DarkMatterRelayBlock::new);
	public static final DeferredBlock<Block> COMBUSTION_GENERATOR = REGISTRY.register("combustion_generator", CombustionGeneratorBlock::new);
	public static final DeferredBlock<Block> DARK_MATTER_SOLAR_PANEL = REGISTRY.register("dark_matter_solar_panel", DarkMatterSolarPanelBlock::new);
	public static final DeferredBlock<Block> SPIDER_EGG = REGISTRY.register("spider_egg", SpiderEggBlock::new);
	public static final DeferredBlock<Block> COMBUSTION_GENERATOR_MK_2 = REGISTRY.register("combustion_generator_mk_2", CombustionGeneratorMk2Block::new);
	public static final DeferredBlock<Block> MATTER_FUSION_REACTOR_2 = REGISTRY.register("matter_fusion_reactor_2", MatterFusionReactor2Block::new);
	public static final DeferredBlock<Block> DUPLICATOR = REGISTRY.register("duplicator", DuplicatorBlock::new);
	public static final DeferredBlock<Block> MOB_ATTACKER = REGISTRY.register("mob_attacker", MobAttackerBlock::new);
	public static final DeferredBlock<Block> PROJECTILE_REMOVER = REGISTRY.register("projectile_remover", ProjectileRemoverBlock::new);
	public static final DeferredBlock<Block> DARK_MATTER_ASSEMBLER = REGISTRY.register("dark_matter_assembler", DarkMatterAssemblerBlock::new);
	public static final DeferredBlock<Block> CLEVER_MACHINE_FRAME = REGISTRY.register("clever_machine_frame", CleverMachineFrameBlock::new);
	public static final DeferredBlock<Block> DIAMOND_GENERATOR = REGISTRY.register("diamond_generator", DiamondGeneratorBlock::new);
	public static final DeferredBlock<Block> SUPER_MAGMA = REGISTRY.register("super_magma", SuperMagmaBlock::new);
	public static final DeferredBlock<Block> INFERNO_MATTER_BLOCK = REGISTRY.register("inferno_matter_block", InfernoMatterBlockBlock::new);
	public static final DeferredBlock<Block> TRACKER_DEFENDER_MK_3 = REGISTRY.register("tracker_defender_mk_3", TrackerDefenderMk3Block::new);
	public static final DeferredBlock<Block> INFERNO_MATTER_SOLAR_PANEL = REGISTRY.register("inferno_matter_solar_panel", InfernoMatterSolarPanelBlock::new);
	public static final DeferredBlock<Block> INFERNO_MATTER_RELAY = REGISTRY.register("inferno_matter_relay", InfernoMatterRelayBlock::new);
	public static final DeferredBlock<Block> COMBUSTION_GENERATOR_MK_3 = REGISTRY.register("combustion_generator_mk_3", CombustionGeneratorMk3Block::new);
	public static final DeferredBlock<Block> MATTER_FUSION_REACTOR_3 = REGISTRY.register("matter_fusion_reactor_3", MatterFusionReactor3Block::new);
	public static final DeferredBlock<Block> MATTER_CATALYST_FOUNDATION_1X = REGISTRY.register("matter_catalyst_foundation_1x", MatterCatalystFoundation1xBlock::new);
	public static final DeferredBlock<Block> MATTER_CATALYST_FOUNDATION_2X = REGISTRY.register("matter_catalyst_foundation_2x", MatterCatalystFoundation2xBlock::new);
	public static final DeferredBlock<Block> MATTER_CATALYST_FOUNDATION_3X = REGISTRY.register("matter_catalyst_foundation_3x", MatterCatalystFoundation3xBlock::new);
	public static final DeferredBlock<Block> DUPLICATED_BEDROCK = REGISTRY.register("duplicated_bedrock", DuplicatedBedrockBlock::new);
	public static final DeferredBlock<Block> SOUL_INSERT_MACHINE_MK_2 = REGISTRY.register("soul_insert_machine_mk_2", SoulInsertMachineMk2Block::new);
	public static final DeferredBlock<Block> SIMULATION_CHAMBER_MK_2 = REGISTRY.register("simulation_chamber_mk_2", SimulationChamberMk2Block::new);
	public static final DeferredBlock<Block> SOUL_INSERT_MACHINE_MK_3 = REGISTRY.register("soul_insert_machine_mk_3", SoulInsertMachineMk3Block::new);
	public static final DeferredBlock<Block> SIMULATION_CHAMBER_MK_3 = REGISTRY.register("simulation_chamber_mk_3", SimulationChamberMK3Block::new);
	public static final DeferredBlock<Block> DARK_MATTER_GENERATOR_MK_2 = REGISTRY.register("dark_matter_generator_mk_2", DarkMatterGeneratorMk2Block::new);
	public static final DeferredBlock<Block> DARK_MATTER_GENERATOR_MK_3 = REGISTRY.register("dark_matter_generator_mk_3", DarkMatterGeneratorMk3Block::new);
	public static final DeferredBlock<Block> FORCE_EMITTER = REGISTRY.register("force_emitter", ForceEmitterBlock::new);
	public static final DeferredBlock<Block> DRAGON_MATTER_BLOCK = REGISTRY.register("dragon_matter_block", DragonMatterBlockBlock::new);
	public static final DeferredBlock<Block> BLACK_HOLE_MATTER_BLOCK_4X = REGISTRY.register("black_hole_matter_block_4x", BlackHoleMatterBlock4xBlock::new);
	public static final DeferredBlock<Block> BLACK_HOLE_MATTER_BLOCK_5X = REGISTRY.register("black_hole_matter_block_5x", BlackHoleMatterBlock5xBlock::new);
	public static final DeferredBlock<Block> DRAGON_MATTER_SOLAR_PANEL = REGISTRY.register("dragon_matter_solar_panel", DragonMatterSolarPanelBlock::new);
	public static final DeferredBlock<Block> TRACKER_DEFENDER_MK_4 = REGISTRY.register("tracker_defender_mk_4", TrackerDefenderMk4Block::new);
	public static final DeferredBlock<Block> DRAGON_MACHINE_FRAME = REGISTRY.register("dragon_machine_frame", DragonMachineFrameBlock::new);
	public static final DeferredBlock<Block> OMEGA_D_CORE_STABILIZER = REGISTRY.register("omega_d_core_stabilizer", OmegaDCoreStabilizerBlock::new);
	public static final DeferredBlock<Block> OMEGA_D_CORE = REGISTRY.register("omega_d_core", OmegaDCoreBlock::new);
	public static final DeferredBlock<Block> DRAGON_MATTER_RELAY = REGISTRY.register("dragon_matter_relay", DragonMatterRelayBlock::new);
	public static final DeferredBlock<Block> INFERNO_ENERGY_CUBE = REGISTRY.register("inferno_energy_cube", InfernoEnergyCubeBlock::new);
	public static final DeferredBlock<Block> DRAGON_ENERGY_CUBE = REGISTRY.register("dragon_energy_cube", DragonEnergyCubeBlock::new);
	public static final DeferredBlock<Block> ICE_MAKER = REGISTRY.register("ice_maker", IceMakerBlock::new);
	public static final DeferredBlock<Block> DRAGON_INCUBATOR = REGISTRY.register("dragon_incubator", DragonIncubatorBlock::new);
	public static final DeferredBlock<Block> WITHER_MATTER_BLOCK = REGISTRY.register("wither_matter_block", WitherMatterBlockBlock::new);
	public static final DeferredBlock<Block> WITHER_ENERGY_CUBE = REGISTRY.register("wither_energy_cube", WitherEnergyCubeBlock::new);
	public static final DeferredBlock<Block> COMBUSTION_GENERATOR_MK_4 = REGISTRY.register("combustion_generator_mk_4", CombustionGeneratorMk4Block::new);
	public static final DeferredBlock<Block> MATTER_FUSION_REACTOR_4 = REGISTRY.register("matter_fusion_reactor_4", MatterFusionReactor4Block::new);
	public static final DeferredBlock<Block> WITHER_MATTER_SOLAR_PANEL = REGISTRY.register("wither_matter_solar_panel", WitherMatterSolarPanelBlock::new);
	public static final DeferredBlock<Block> WITHER_MATTER_RELAY = REGISTRY.register("wither_matter_relay", WitherMatterRelayBlock::new);
	public static final DeferredBlock<Block> COMBUSTION_GENERATOR_MK_5 = REGISTRY.register("combustion_generator_mk_5", CombustionGeneratorMk5Block::new);
	public static final DeferredBlock<Block> MATTER_FUSION_REACTOR_5 = REGISTRY.register("matter_fusion_reactor_5", MatterFusionReactor5Block::new);
	public static final DeferredBlock<Block> WIRELESS_AUTO_MENDER = REGISTRY.register("wireless_auto_mender", WirelessAutoMenderBlock::new);
	public static final DeferredBlock<Block> TRACKER_DEFENDER_MK_5 = REGISTRY.register("tracker_defender_mk_5", TrackerDefenderMk5Block::new);
	public static final DeferredBlock<Block> ALLOY_SMELTER = REGISTRY.register("alloy_smelter", AlloySmelterBlock::new);
	public static final DeferredBlock<Block> HYPER_GOLD_INGOT_BLOCK = REGISTRY.register("hyper_gold_ingot_block", HyperGoldIngotBlockBlock::new);
	public static final DeferredBlock<Block> BLACK_HOLE_MATTER_INGOT_BLOCK = REGISTRY.register("black_hole_matter_ingot_block", BlackHoleMatterIngotBlockBlock::new);
	public static final DeferredBlock<Block> DARK_MATTER_INGOT_BLOCK = REGISTRY.register("dark_matter_ingot_block", DarkMatterIngotBlockBlock::new);
	public static final DeferredBlock<Block> INFERNO_MATTER_INGOT_BLOCK = REGISTRY.register("inferno_matter_ingot_block", InfernoMatterIngotBlockBlock::new);
	public static final DeferredBlock<Block> DRAGON_MATTER_INGOT_BLOCK = REGISTRY.register("dragon_matter_ingot_block", DragonMatterIngotBlockBlock::new);
	public static final DeferredBlock<Block> WITHER_MATTER_INGOT_BLOCK = REGISTRY.register("wither_matter_ingot_block", WitherMatterIngotBlockBlock::new);
	public static final DeferredBlock<Block> QUANTUM_INFUSER = REGISTRY.register("quantum_infuser", QuantumInfuserBlock::new);
	public static final DeferredBlock<Block> ENERGY_STABILIZER = REGISTRY.register("energy_stabilizer", EnergyStabilizerBlock::new);
	public static final DeferredBlock<Block> PERFECT_MATTER_FOUNDATION = REGISTRY.register("perfect_matter_foundation", PerfectMatterFoundationBlock::new);
	public static final DeferredBlock<Block> PERFECT_MATTER_BLOCK = REGISTRY.register("perfect_matter_block", PerfectMatterBlockBlock::new);
	public static final DeferredBlock<Block> INFINITY_MATRIX = REGISTRY.register("infinity_matrix", InfinityMatrixBlock::new);
	public static final DeferredBlock<Block> INFINITY_SIMULATION_CHAMBER = REGISTRY.register("infinity_simulation_chamber", InfinitySimulationChamberBlock::new);
	public static final DeferredBlock<Block> WITHER_INCUBATOR = REGISTRY.register("wither_incubator", WitherIncubatorBlock::new);
	public static final DeferredBlock<Block> DARK_MATTER_GENERATOR_MK_4 = REGISTRY.register("dark_matter_generator_mk_4", DarkMatterGeneratorMk4Block::new);
	public static final DeferredBlock<Block> INFINITE_WATER_SOURCE = REGISTRY.register("infinite_water_source", InfiniteWaterSourceBlock::new);
	public static final DeferredBlock<Block> INFINITE_LAVA_SOURCE = REGISTRY.register("infinite_lava_source", InfiniteLavaSourceBlock::new);
	public static final DeferredBlock<Block> DARK_MATTER_GENERATOR_MK_5 = REGISTRY.register("dark_matter_generator_mk_5", DarkMatterGeneratorMk5Block::new);
	public static final DeferredBlock<Block> COPPER_GENERATOR = REGISTRY.register("copper_generator", CopperGeneratorBlock::new);
	public static final DeferredBlock<Block> APPLE_CULTIVATOR_MK_1 = REGISTRY.register("apple_cultivator_mk_1", AppleCultivatorMk1Block::new);
	public static final DeferredBlock<Block> APPLE_CULTIVATOR_MK_2 = REGISTRY.register("apple_cultivator_mk_2", AppleCultivatorMk2Block::new);
	public static final DeferredBlock<Block> MATTER_CATALYST_COMPRESSOR_1 = REGISTRY.register("matter_catalyst_compressor_1", MatterCatalystCompressor1Block::new);
	public static final DeferredBlock<Block> MATTER_CATALYST_COMPRESSOR_2 = REGISTRY.register("matter_catalyst_compressor_2", MatterCatalystCompressor2Block::new);
	public static final DeferredBlock<Block> MATTER_CATALYST_COMPRESSOR_3 = REGISTRY.register("matter_catalyst_compressor_3", MatterCatalystCompressor3Block::new);
	public static final DeferredBlock<Block> IRON_GENERATOR = REGISTRY.register("iron_generator", IronGeneratorBlock::new);
	public static final DeferredBlock<Block> REDSTONE_GENERATOR = REGISTRY.register("redstone_generator", RedstoneGeneratorBlock::new);
	public static final DeferredBlock<Block> ULTIMATE_BLOCK = REGISTRY.register("ultimate_block", UltimateBlockBlock::new);
	public static final DeferredBlock<Block> ZIO_INSERTER = REGISTRY.register("zio_inserter", ZioInserterBlock::new);
	public static final DeferredBlock<Block> ZIO_EXPORTER = REGISTRY.register("zio_exporter", ZioExporterBlock::new);
	public static final DeferredBlock<Block> DARK_MATTER_QUANTUM_VAULT = REGISTRY.register("dark_matter_quantum_vault", DarkMatterQuantumVaultBlock::new);
	public static final DeferredBlock<Block> INFINITE_COBBLESTONE_SOURCE = REGISTRY.register("infinite_cobblestone_source", InfiniteCobblestoneSourceBlock::new);
	public static final DeferredBlock<Block> FICTIONAL_PLANET = REGISTRY.register("fictional_planet", FictionalPlanetBlock::new);
	public static final DeferredBlock<Block> INFERNO_ENERGY_ACCEPTOR = REGISTRY.register("inferno_energy_acceptor", InfernoEnergyAcceptorBlock::new);
	public static final DeferredBlock<Block> INFERNO_MINING_CONTROLLER = REGISTRY.register("inferno_mining_controller", InfernoMiningControllerBlock::new);
	public static final DeferredBlock<Block> INFERNO_ITEM_OUTPUT_BLOCK = REGISTRY.register("inferno_item_output_block", InfernoItemOutputBlockBlock::new);
	public static final DeferredBlock<Block> INFERNO_MINING_CASING = REGISTRY.register("inferno_mining_casing", InfernoMiningCasingBlock::new);
	public static final DeferredBlock<Block> INFERNO_QUANTUM_DRILL = REGISTRY.register("inferno_quantum_drill", InfernoQuantumDrillBlock::new);
	public static final DeferredBlock<Block> INFERNO_FICTIONAL_PLANET_MODEL_MODIFIER = REGISTRY.register("inferno_fictional_planet_model_modifier", InfernoFictionalPlanetModelModifierBlock::new);
	public static final DeferredBlock<Block> RAW_TUNGSTEN_BLOCK = REGISTRY.register("raw_tungsten_block", RawTungstenBlockBlock::new);
	public static final DeferredBlock<Block> TUNGSTEN_BLOCK = REGISTRY.register("tungsten_block", TungstenBlockBlock::new);
	public static final DeferredBlock<Block> ARTIFICIAL_SUN = REGISTRY.register("artificial_sun", ArtificialSunBlock::new);
	public static final DeferredBlock<Block> PLANETARY_REGULATOR = REGISTRY.register("planetary_regulator", PlanetaryRegulatorBlock::new);
	public static final DeferredBlock<Block> DRAGON_MINING_CONTROLLER = REGISTRY.register("dragon_mining_controller", DragonMiningControllerBlock::new);
	public static final DeferredBlock<Block> DRAGON_ENERGY_ACCEPTOR = REGISTRY.register("dragon_energy_acceptor", DragonEnergyAcceptorBlock::new);
	public static final DeferredBlock<Block> DRAGON_MINING_CASING = REGISTRY.register("dragon_mining_casing", DragonMiningCasingBlock::new);
	public static final DeferredBlock<Block> DRAGON_QUANTUM_DRILL = REGISTRY.register("dragon_quantum_drill", DragonQuantumDrillBlock::new);
	public static final DeferredBlock<Block> DRAGON_ITEM_OUTPUT_BLOCK = REGISTRY.register("dragon_item_output_block", DragonItemOutputBlockBlock::new);
	public static final DeferredBlock<Block> QUANTUM_ANCHOR = REGISTRY.register("quantum_anchor", QuantumAnchorBlock::new);
	public static final DeferredBlock<Block> DARK_MATTER_BOILER_CASING = REGISTRY.register("dark_matter_boiler_casing", DarkMatterBoilerCasingBlock::new);
	public static final DeferredBlock<Block> DARK_MATTER_HEAT_CONDUCTION_COIL = REGISTRY.register("dark_matter_heat_conduction_coil", DarkMatterHeatConductionCoilBlock::new);
	public static final DeferredBlock<Block> DARK_FLUID_INPUT_BLOCK = REGISTRY.register("dark_fluid_input_block", DarkFluidInputBlockBlock::new);
	public static final DeferredBlock<Block> DARK_ITEM_OUTPUT_BLOCK = REGISTRY.register("dark_item_output_block", DarkItemOutputBlockBlock::new);
	public static final DeferredBlock<Block> MATTER_CATALYST_BOILER_CONTROLLER = REGISTRY.register("matter_catalyst_boiler_controller", MatterCatalystBoilerControllerBlock::new);
	public static final DeferredBlock<Block> DARK_MATTER_GROWTH_ACCELERATOR = REGISTRY.register("dark_matter_growth_accelerator", DarkMatterGrowthAcceleratorBlock::new);
	public static final DeferredBlock<Block> INFINITY_TRACKER_DEFENDER = REGISTRY.register("infinity_tracker_defender", InfinityTrackerDefenderBlock::new);
	public static final DeferredBlock<Block> SUPER_SMELTING_BLOCK = REGISTRY.register("super_smelting_block", SuperSmeltingBlockBlock::new);
	public static final DeferredBlock<Block> DRAGON_QSS_CONTROLLER = REGISTRY.register("dragon_qss_controller", DragonQssControllerBlock::new);
	public static final DeferredBlock<Block> DRAGON_QSS_CASING = REGISTRY.register("dragon_qss_casing", DragonQssCasingBlock::new);
	public static final DeferredBlock<Block> DRAGON_QSS_STABILIZER = REGISTRY.register("dragon_qss_stabilizer", DragonQssStabilizerBlock::new);
	public static final DeferredBlock<Block> DRAGON_QSS_QUBIT_MEMORY = REGISTRY.register("dragon_qss_qubit_memory", DragonQssQubitMemoryBlock::new);
	public static final DeferredBlock<Block> DRAGON_QSS_ERROR_SOLVER = REGISTRY.register("dragon_qss_error_solver", DragonQssErrorSolverBlock::new);
	public static final DeferredBlock<Block> DRAGON_QSS_OUTPUT_BLOCK = REGISTRY.register("dragon_qss_output_block", DragonQssOutputBlockBlock::new);
	public static final DeferredBlock<Block> REINFORCED_REDSTONE_BLOCK = REGISTRY.register("reinforced_redstone_block", ReinforcedRedstoneBlockBlock::new);
	public static final DeferredBlock<Block> TEAR_EXTRACTOR_MK_1 = REGISTRY.register("tear_extractor_mk_1", TearExtractorMk1Block::new);
	public static final DeferredBlock<Block> NETHER_STAR_BLOCK = REGISTRY.register("nether_star_block", NetherStarBlockBlock::new);
	public static final DeferredBlock<Block> TUNGSTEN_CRYSTAL_MATRIX_BLOCK = REGISTRY.register("tungsten_crystal_matrix_block", TungstenCrystalMatrixBlockBlock::new);
	public static final DeferredBlock<Block> WITHER_MACHINE_FRAME = REGISTRY.register("wither_machine_frame", WitherMachineFrameBlock::new);
	public static final DeferredBlock<Block> INFERNO_MATTER_ASSEMBLER = REGISTRY.register("inferno_matter_assembler", InfernoMatterAssemblerBlock::new);
	public static final DeferredBlock<Block> KILLMKILL_97_BLOCK = REGISTRY.register("killmkill_97_block", Killmkill97BlockBlock::new);
	public static final DeferredBlock<Block> TUNGSTEN_FURNACE = REGISTRY.register("tungsten_furnace", TungstenFurnaceBlock::new);
	public static final DeferredBlock<Block> DUPLICATOR_MK_2 = REGISTRY.register("duplicator_mk_2", DuplicatorMk2Block::new);
	public static final DeferredBlock<Block> SUPER_LAVA = REGISTRY.register("super_lava", SuperLavaBlock::new);
	public static final DeferredBlock<Block> MYSTERY_CUBE = REGISTRY.register("mystery_cube", MysteryCubeBlock::new);
	public static final DeferredBlock<Block> HYPER_STONE = REGISTRY.register("hyper_stone", HyperStoneBlock::new);
	public static final DeferredBlock<Block> HYPER_NETHER_BRICKS = REGISTRY.register("hyper_nether_bricks", HyperNetherBricksBlock::new);
	public static final DeferredBlock<Block> END_MYSTERY_CUBE = REGISTRY.register("end_mystery_cube", EndMysteryCubeBlock::new);
	public static final DeferredBlock<Block> BLACK_HOLE_MATTER_SAPLING = REGISTRY.register("black_hole_matter_sapling", BlackHoleMatterSaplingBlock::new);
	public static final DeferredBlock<Block> DARK_MATTER_SAPLING = REGISTRY.register("dark_matter_sapling", DarkMatterSaplingBlock::new);
	public static final DeferredBlock<Block> INFERNO_MATTER_SAPLING = REGISTRY.register("inferno_matter_sapling", InfernoMatterSaplingBlock::new);
	public static final DeferredBlock<Block> TRACKER_INCUBATOR = REGISTRY.register("tracker_incubator", TrackerIncubatorBlock::new);
	public static final DeferredBlock<Block> GOLDEN_SAPLING = REGISTRY.register("golden_sapling", GoldenSaplingBlock::new);
	public static final DeferredBlock<Block> CONTAINED_SUPER_TRACKER = REGISTRY.register("contained_super_tracker", ContainedSuperTrackerBlock::new);
	public static final DeferredBlock<Block> TRACKER_CONTAINMENT_CAGE = REGISTRY.register("tracker_containment_cage", TrackerContainmentCageBlock::new);
	public static final DeferredBlock<Block> TAMABLE_TRACKER_CUBE = REGISTRY.register("tamable_tracker_cube", TamableTrackerCubeBlock::new);
	public static final DeferredBlock<Block> ARTIFICIAL_NEUTRON_STAR = REGISTRY.register("artificial_neutron_star", ArtificialNeutronStarBlock::new);
	public static final DeferredBlock<Block> SOLAR_RESIDUUM_COLLECTOR = REGISTRY.register("solar_residuum_collector", SolarResiduumCollectorBlock::new);
	public static final DeferredBlock<Block> HFE_UP_SCALER = REGISTRY.register("hfe_up_scaler", HFEUpScalerBlock::new);
	public static final DeferredBlock<Block> WITHER_HFE_CUBE = REGISTRY.register("wither_hfe_cube", WitherHfeCubeBlock::new);
	public static final DeferredBlock<Block> HFE_DOWN_SCALER = REGISTRY.register("hfe_down_scaler", HfeDownScalerBlock::new);
	public static final DeferredBlock<Block> CREATIVE_HFE_GENERATOR = REGISTRY.register("creative_hfe_generator", CreativeHFEGeneratorBlock::new);
	public static final DeferredBlock<Block> WITHER_MATTER_HFE_RELAY = REGISTRY.register("wither_matter_hfe_relay", WitherMatterHFERelayBlock::new);
	public static final DeferredBlock<Block> DYSON_RING_CONTROLLER = REGISTRY.register("dyson_ring_controller", DysonRingControllerBlock::new);
	public static final DeferredBlock<Block> DYSON_RING_SOLAR_PANEL = REGISTRY.register("dyson_ring_solar_panel", DysonRingSolarPanelBlock::new);
	public static final DeferredBlock<Block> QUANTUM_IGNITER = REGISTRY.register("quantum_igniter", QuantumIgniterBlock::new);
	public static final DeferredBlock<Block> PERFECT_HFE_CUBE = REGISTRY.register("perfect_hfe_cube", PerfectHFECubeBlock::new);
	public static final DeferredBlock<Block> MOLECULAR_ASSEMBLER = REGISTRY.register("molecular_assembler", MolecularAssemblerBlock::new);
	public static final DeferredBlock<Block> MOLECULAR_SOLVENT = REGISTRY.register("molecular_solvent", MolecularSolventBlock::new);
	public static final DeferredBlock<Block> MOLECULAR_DISSOLVER = REGISTRY.register("molecular_dissolver", MolecularDissolverBlock::new);
	public static final DeferredBlock<Block> MOLECULAR_MATTER_RESYNTHESIZER = REGISTRY.register("molecular_matter_resynthesizer", MolecularMatterResynthesizerBlock::new);
	public static final DeferredBlock<Block> MOLECULAR_ALLOYING_FORGE = REGISTRY.register("molecular_alloying_forge", MolecularAlloyingForgeBlock::new);
	public static final DeferredBlock<Block> MOLECULAR_COMPRESSION_STATION = REGISTRY.register("molecular_compression_station", MolecularCompressionStationBlock::new);
	public static final DeferredBlock<Block> MICROVERSE_SIMULATOR_CONTROLLER = REGISTRY.register("microverse_simulator_controller", MicroverseSimulatorControllerBlock::new);
	public static final DeferredBlock<Block> MICROVERSE_CASING = REGISTRY.register("microverse_casing", MicroverseCasingBlock::new);
	public static final DeferredBlock<Block> MICROVERSE_ITEM_OUTPUT_BLOCK = REGISTRY.register("microverse_item_output_block", MicroverseItemOutputBlockBlock::new);
	public static final DeferredBlock<Block> MICROVERSE_INPUT_BLOCK = REGISTRY.register("microverse_input_block", MicroverseInputBlockBlock::new);
	public static final DeferredBlock<Block> MICROVERSE_STABILIZER = REGISTRY.register("microverse_stabilizer", MicroverseStabilizerBlock::new);
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
