
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.extrememonsters.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.Block;
import net.minecraft.core.registries.BuiltInRegistries;

import net.mcreator.extrememonsters.block.entity.ZioInserterBlockEntity;
import net.mcreator.extrememonsters.block.entity.ZioExporterBlockEntity;
import net.mcreator.extrememonsters.block.entity.WitherMatterSolarPanelBlockEntity;
import net.mcreator.extrememonsters.block.entity.WitherMatterRelayBlockEntity;
import net.mcreator.extrememonsters.block.entity.WitherMatterHFERelayBlockEntity;
import net.mcreator.extrememonsters.block.entity.WitherIncubatorBlockEntity;
import net.mcreator.extrememonsters.block.entity.WitherHfeCubeBlockEntity;
import net.mcreator.extrememonsters.block.entity.WitherEnergyCubeBlockEntity;
import net.mcreator.extrememonsters.block.entity.WirelessAutoMenderBlockEntity;
import net.mcreator.extrememonsters.block.entity.TungstenFurnaceBlockEntity;
import net.mcreator.extrememonsters.block.entity.TrackerIncubatorBlockEntity;
import net.mcreator.extrememonsters.block.entity.TrackerDefenderMk5BlockEntity;
import net.mcreator.extrememonsters.block.entity.TrackerDefenderMk4BlockEntity;
import net.mcreator.extrememonsters.block.entity.TrackerDefenderMk3BlockEntity;
import net.mcreator.extrememonsters.block.entity.TrackerDefenderMk2BlockEntity;
import net.mcreator.extrememonsters.block.entity.TrackerDefenderBlockEntity;
import net.mcreator.extrememonsters.block.entity.TrackerContainmentCageTileEntity;
import net.mcreator.extrememonsters.block.entity.TearExtractorMk1BlockEntity;
import net.mcreator.extrememonsters.block.entity.SuperSmeltingBlockBlockEntity;
import net.mcreator.extrememonsters.block.entity.SuperMagmaBlockEntity;
import net.mcreator.extrememonsters.block.entity.SpiderEggBlockEntity;
import net.mcreator.extrememonsters.block.entity.SoulInsertMachineMk3BlockEntity;
import net.mcreator.extrememonsters.block.entity.SoulInsertMachineMk2BlockEntity;
import net.mcreator.extrememonsters.block.entity.SoulInsertMachineBlockEntity;
import net.mcreator.extrememonsters.block.entity.SolarResiduumCollectorBlockEntity;
import net.mcreator.extrememonsters.block.entity.SimulationChamberMk2BlockEntity;
import net.mcreator.extrememonsters.block.entity.SimulationChamberMK3BlockEntity;
import net.mcreator.extrememonsters.block.entity.SimulationChamberBlockEntity;
import net.mcreator.extrememonsters.block.entity.RedstoneGeneratorBlockEntity;
import net.mcreator.extrememonsters.block.entity.QuantumInfuserBlockEntity;
import net.mcreator.extrememonsters.block.entity.QuantumIgniterBlockEntity;
import net.mcreator.extrememonsters.block.entity.QuantumAnchorBlockEntity;
import net.mcreator.extrememonsters.block.entity.ProjectileRemoverBlockEntity;
import net.mcreator.extrememonsters.block.entity.PlanetaryRegulatorTileEntity;
import net.mcreator.extrememonsters.block.entity.PerfectMatterFoundationBlockEntity;
import net.mcreator.extrememonsters.block.entity.PerfectHFECubeBlockEntity;
import net.mcreator.extrememonsters.block.entity.OmegaDCoreStabilizerBlockEntity;
import net.mcreator.extrememonsters.block.entity.OmegaDCoreBlockEntity;
import net.mcreator.extrememonsters.block.entity.NetheriteFusionReactorBlockEntity;
import net.mcreator.extrememonsters.block.entity.MolecularMatterResynthesizerBlockEntity;
import net.mcreator.extrememonsters.block.entity.MolecularDissolverBlockEntity;
import net.mcreator.extrememonsters.block.entity.MolecularCompressionStationBlockEntity;
import net.mcreator.extrememonsters.block.entity.MolecularAssemblerBlockEntity;
import net.mcreator.extrememonsters.block.entity.MolecularAlloyingForgeBlockEntity;
import net.mcreator.extrememonsters.block.entity.MobSeduceBlockEntity;
import net.mcreator.extrememonsters.block.entity.MobAttackerBlockEntity;
import net.mcreator.extrememonsters.block.entity.MicroverseSimulatorControllerBlockEntity;
import net.mcreator.extrememonsters.block.entity.MicroverseItemOutputBlockBlockEntity;
import net.mcreator.extrememonsters.block.entity.MicroverseInputBlockBlockEntity;
import net.mcreator.extrememonsters.block.entity.MatterFusionReactor5BlockEntity;
import net.mcreator.extrememonsters.block.entity.MatterFusionReactor4BlockEntity;
import net.mcreator.extrememonsters.block.entity.MatterFusionReactor3BlockEntity;
import net.mcreator.extrememonsters.block.entity.MatterFusionReactor2BlockEntity;
import net.mcreator.extrememonsters.block.entity.MatterFusionReactor1BlockEntity;
import net.mcreator.extrememonsters.block.entity.MatterCatalystMakerBlockEntity;
import net.mcreator.extrememonsters.block.entity.MatterCatalystCompressor3BlockEntity;
import net.mcreator.extrememonsters.block.entity.MatterCatalystCompressor2BlockEntity;
import net.mcreator.extrememonsters.block.entity.MatterCatalystCompressor1BlockEntity;
import net.mcreator.extrememonsters.block.entity.MatterCatalystBoilerControllerBlockEntity;
import net.mcreator.extrememonsters.block.entity.IronGeneratorBlockEntity;
import net.mcreator.extrememonsters.block.entity.InfinityTrackerDefenderBlockEntity;
import net.mcreator.extrememonsters.block.entity.InfinitySimulationChamberBlockEntity;
import net.mcreator.extrememonsters.block.entity.InfinityMatrixBlockEntity;
import net.mcreator.extrememonsters.block.entity.InfiniteWaterSourceBlockEntity;
import net.mcreator.extrememonsters.block.entity.InfiniteLavaSourceBlockEntity;
import net.mcreator.extrememonsters.block.entity.InfiniteCobblestoneSourceBlockEntity;
import net.mcreator.extrememonsters.block.entity.InfernoMiningControllerBlockEntity;
import net.mcreator.extrememonsters.block.entity.InfernoMatterSolarPanelBlockEntity;
import net.mcreator.extrememonsters.block.entity.InfernoMatterRelayBlockEntity;
import net.mcreator.extrememonsters.block.entity.InfernoMatterAssemblerBlockEntity;
import net.mcreator.extrememonsters.block.entity.InfernoItemOutputBlockBlockEntity;
import net.mcreator.extrememonsters.block.entity.InfernoFictionalPlanetModelModifierBlockEntity;
import net.mcreator.extrememonsters.block.entity.InfernoEnergyCubeBlockEntity;
import net.mcreator.extrememonsters.block.entity.InfernoEnergyAcceptorBlockEntity;
import net.mcreator.extrememonsters.block.entity.IceMakerBlockEntity;
import net.mcreator.extrememonsters.block.entity.HfeDownScalerBlockEntity;
import net.mcreator.extrememonsters.block.entity.HFEUpScalerBlockEntity;
import net.mcreator.extrememonsters.block.entity.ForceEmitterBlockEntity;
import net.mcreator.extrememonsters.block.entity.FictionalPlanetTileEntity;
import net.mcreator.extrememonsters.block.entity.DysonRingControllerBlockEntity;
import net.mcreator.extrememonsters.block.entity.DuplicatorMk2BlockEntity;
import net.mcreator.extrememonsters.block.entity.DuplicatorBlockEntity;
import net.mcreator.extrememonsters.block.entity.DragonQssOutputBlockBlockEntity;
import net.mcreator.extrememonsters.block.entity.DragonQssControllerBlockEntity;
import net.mcreator.extrememonsters.block.entity.DragonMiningControllerBlockEntity;
import net.mcreator.extrememonsters.block.entity.DragonMatterSolarPanelBlockEntity;
import net.mcreator.extrememonsters.block.entity.DragonMatterRelayBlockEntity;
import net.mcreator.extrememonsters.block.entity.DragonItemOutputBlockBlockEntity;
import net.mcreator.extrememonsters.block.entity.DragonIncubatorBlockEntity;
import net.mcreator.extrememonsters.block.entity.DragonEnergyCubeBlockEntity;
import net.mcreator.extrememonsters.block.entity.DragonEnergyAcceptorBlockEntity;
import net.mcreator.extrememonsters.block.entity.DiamondGeneratorBlockEntity;
import net.mcreator.extrememonsters.block.entity.DarkMatterSolarPanelBlockEntity;
import net.mcreator.extrememonsters.block.entity.DarkMatterRelayBlockEntity;
import net.mcreator.extrememonsters.block.entity.DarkMatterQuantumVaultBlockEntity;
import net.mcreator.extrememonsters.block.entity.DarkMatterGrowthAcceleratorBlockEntity;
import net.mcreator.extrememonsters.block.entity.DarkMatterGeneratorMk5BlockEntity;
import net.mcreator.extrememonsters.block.entity.DarkMatterGeneratorMk4BlockEntity;
import net.mcreator.extrememonsters.block.entity.DarkMatterGeneratorMk3BlockEntity;
import net.mcreator.extrememonsters.block.entity.DarkMatterGeneratorMk2BlockEntity;
import net.mcreator.extrememonsters.block.entity.DarkMatterGeneratorBlockEntity;
import net.mcreator.extrememonsters.block.entity.DarkMatterAssemblerBlockEntity;
import net.mcreator.extrememonsters.block.entity.DarkItemOutputBlockBlockEntity;
import net.mcreator.extrememonsters.block.entity.DarkFluidInputBlockBlockEntity;
import net.mcreator.extrememonsters.block.entity.CreativeHFEGeneratorBlockEntity;
import net.mcreator.extrememonsters.block.entity.CreativeGeneratorBlockEntity;
import net.mcreator.extrememonsters.block.entity.CopperGeneratorBlockEntity;
import net.mcreator.extrememonsters.block.entity.ContainedSuperTrackerTileEntity;
import net.mcreator.extrememonsters.block.entity.CombustionGeneratorMk5BlockEntity;
import net.mcreator.extrememonsters.block.entity.CombustionGeneratorMk4BlockEntity;
import net.mcreator.extrememonsters.block.entity.CombustionGeneratorMk3BlockEntity;
import net.mcreator.extrememonsters.block.entity.CombustionGeneratorMk2BlockEntity;
import net.mcreator.extrememonsters.block.entity.CombustionGeneratorBlockEntity;
import net.mcreator.extrememonsters.block.entity.BlackHoleMatterSolarPlanelBlockEntity;
import net.mcreator.extrememonsters.block.entity.BlackHoleMatterRelayBlockEntity;
import net.mcreator.extrememonsters.block.entity.BlackHoleMatterAssemblerBlockEntity;
import net.mcreator.extrememonsters.block.entity.ArtificialSunTileEntity;
import net.mcreator.extrememonsters.block.entity.ArtificialNeutronStarTileEntity;
import net.mcreator.extrememonsters.block.entity.AppleCultivatorMk2BlockEntity;
import net.mcreator.extrememonsters.block.entity.AppleCultivatorMk1BlockEntity;
import net.mcreator.extrememonsters.block.entity.AlloySmelterBlockEntity;
import net.mcreator.extrememonsters.ExtremeMonstersMod;

@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD)
public class ExtremeMonstersModBlockEntities {
	public static final DeferredRegister<BlockEntityType<?>> REGISTRY = DeferredRegister.create(BuiltInRegistries.BLOCK_ENTITY_TYPE, ExtremeMonstersMod.MODID);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DARK_MATTER_GENERATOR = register("dark_matter_generator", ExtremeMonstersModBlocks.DARK_MATTER_GENERATOR, DarkMatterGeneratorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> BLACK_HOLE_MATTER_SOLAR_PLANEL = register("black_hole_matter_solar_planel", ExtremeMonstersModBlocks.BLACK_HOLE_MATTER_SOLAR_PLANEL,
			BlackHoleMatterSolarPlanelBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> NETHERITE_FUSION_REACTOR = register("netherite_fusion_reactor", ExtremeMonstersModBlocks.NETHERITE_FUSION_REACTOR, NetheriteFusionReactorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> SOUL_INSERT_MACHINE = register("soul_insert_machine", ExtremeMonstersModBlocks.SOUL_INSERT_MACHINE, SoulInsertMachineBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> SIMULATION_CHAMBER = register("simulation_chamber", ExtremeMonstersModBlocks.SIMULATION_CHAMBER, SimulationChamberBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> BLACK_HOLE_MATTER_ASSEMBLER = register("black_hole_matter_assembler", ExtremeMonstersModBlocks.BLACK_HOLE_MATTER_ASSEMBLER, BlackHoleMatterAssemblerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MOB_SEDUCE = register("mob_seduce", ExtremeMonstersModBlocks.MOB_SEDUCE, MobSeduceBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CREATIVE_GENERATOR = register("creative_generator", ExtremeMonstersModBlocks.CREATIVE_GENERATOR, CreativeGeneratorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> TRACKER_DEFENDER = register("tracker_defender", ExtremeMonstersModBlocks.TRACKER_DEFENDER, TrackerDefenderBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> BLACK_HOLE_MATTER_RELAY = register("black_hole_matter_relay", ExtremeMonstersModBlocks.BLACK_HOLE_MATTER_RELAY, BlackHoleMatterRelayBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MATTER_FUSION_REACTOR_1 = register("matter_fusion_reactor_1", ExtremeMonstersModBlocks.MATTER_FUSION_REACTOR_1, MatterFusionReactor1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MATTER_CATALYST_MAKER = register("matter_catalyst_maker", ExtremeMonstersModBlocks.MATTER_CATALYST_MAKER, MatterCatalystMakerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> TRACKER_DEFENDER_MK_2 = register("tracker_defender_mk_2", ExtremeMonstersModBlocks.TRACKER_DEFENDER_MK_2, TrackerDefenderMk2BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DARK_MATTER_RELAY = register("dark_matter_relay", ExtremeMonstersModBlocks.DARK_MATTER_RELAY, DarkMatterRelayBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> COMBUSTION_GENERATOR = register("combustion_generator", ExtremeMonstersModBlocks.COMBUSTION_GENERATOR, CombustionGeneratorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DARK_MATTER_SOLAR_PANEL = register("dark_matter_solar_panel", ExtremeMonstersModBlocks.DARK_MATTER_SOLAR_PANEL, DarkMatterSolarPanelBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> SPIDER_EGG = register("spider_egg", ExtremeMonstersModBlocks.SPIDER_EGG, SpiderEggBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> COMBUSTION_GENERATOR_MK_2 = register("combustion_generator_mk_2", ExtremeMonstersModBlocks.COMBUSTION_GENERATOR_MK_2, CombustionGeneratorMk2BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MATTER_FUSION_REACTOR_2 = register("matter_fusion_reactor_2", ExtremeMonstersModBlocks.MATTER_FUSION_REACTOR_2, MatterFusionReactor2BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DUPLICATOR = register("duplicator", ExtremeMonstersModBlocks.DUPLICATOR, DuplicatorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MOB_ATTACKER = register("mob_attacker", ExtremeMonstersModBlocks.MOB_ATTACKER, MobAttackerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> PROJECTILE_REMOVER = register("projectile_remover", ExtremeMonstersModBlocks.PROJECTILE_REMOVER, ProjectileRemoverBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DARK_MATTER_ASSEMBLER = register("dark_matter_assembler", ExtremeMonstersModBlocks.DARK_MATTER_ASSEMBLER, DarkMatterAssemblerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DIAMOND_GENERATOR = register("diamond_generator", ExtremeMonstersModBlocks.DIAMOND_GENERATOR, DiamondGeneratorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> SUPER_MAGMA = register("super_magma", ExtremeMonstersModBlocks.SUPER_MAGMA, SuperMagmaBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> TRACKER_DEFENDER_MK_3 = register("tracker_defender_mk_3", ExtremeMonstersModBlocks.TRACKER_DEFENDER_MK_3, TrackerDefenderMk3BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> INFERNO_MATTER_SOLAR_PANEL = register("inferno_matter_solar_panel", ExtremeMonstersModBlocks.INFERNO_MATTER_SOLAR_PANEL, InfernoMatterSolarPanelBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> INFERNO_MATTER_RELAY = register("inferno_matter_relay", ExtremeMonstersModBlocks.INFERNO_MATTER_RELAY, InfernoMatterRelayBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> COMBUSTION_GENERATOR_MK_3 = register("combustion_generator_mk_3", ExtremeMonstersModBlocks.COMBUSTION_GENERATOR_MK_3, CombustionGeneratorMk3BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MATTER_FUSION_REACTOR_3 = register("matter_fusion_reactor_3", ExtremeMonstersModBlocks.MATTER_FUSION_REACTOR_3, MatterFusionReactor3BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> SOUL_INSERT_MACHINE_MK_2 = register("soul_insert_machine_mk_2", ExtremeMonstersModBlocks.SOUL_INSERT_MACHINE_MK_2, SoulInsertMachineMk2BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> SIMULATION_CHAMBER_MK_2 = register("simulation_chamber_mk_2", ExtremeMonstersModBlocks.SIMULATION_CHAMBER_MK_2, SimulationChamberMk2BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> SOUL_INSERT_MACHINE_MK_3 = register("soul_insert_machine_mk_3", ExtremeMonstersModBlocks.SOUL_INSERT_MACHINE_MK_3, SoulInsertMachineMk3BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> SIMULATION_CHAMBER_MK_3 = register("simulation_chamber_mk_3", ExtremeMonstersModBlocks.SIMULATION_CHAMBER_MK_3, SimulationChamberMK3BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DARK_MATTER_GENERATOR_MK_2 = register("dark_matter_generator_mk_2", ExtremeMonstersModBlocks.DARK_MATTER_GENERATOR_MK_2, DarkMatterGeneratorMk2BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DARK_MATTER_GENERATOR_MK_3 = register("dark_matter_generator_mk_3", ExtremeMonstersModBlocks.DARK_MATTER_GENERATOR_MK_3, DarkMatterGeneratorMk3BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> FORCE_EMITTER = register("force_emitter", ExtremeMonstersModBlocks.FORCE_EMITTER, ForceEmitterBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DRAGON_MATTER_SOLAR_PANEL = register("dragon_matter_solar_panel", ExtremeMonstersModBlocks.DRAGON_MATTER_SOLAR_PANEL, DragonMatterSolarPanelBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> TRACKER_DEFENDER_MK_4 = register("tracker_defender_mk_4", ExtremeMonstersModBlocks.TRACKER_DEFENDER_MK_4, TrackerDefenderMk4BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> OMEGA_D_CORE_STABILIZER = register("omega_d_core_stabilizer", ExtremeMonstersModBlocks.OMEGA_D_CORE_STABILIZER, OmegaDCoreStabilizerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> OMEGA_D_CORE = register("omega_d_core", ExtremeMonstersModBlocks.OMEGA_D_CORE, OmegaDCoreBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DRAGON_MATTER_RELAY = register("dragon_matter_relay", ExtremeMonstersModBlocks.DRAGON_MATTER_RELAY, DragonMatterRelayBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> INFERNO_ENERGY_CUBE = register("inferno_energy_cube", ExtremeMonstersModBlocks.INFERNO_ENERGY_CUBE, InfernoEnergyCubeBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DRAGON_ENERGY_CUBE = register("dragon_energy_cube", ExtremeMonstersModBlocks.DRAGON_ENERGY_CUBE, DragonEnergyCubeBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> ICE_MAKER = register("ice_maker", ExtremeMonstersModBlocks.ICE_MAKER, IceMakerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DRAGON_INCUBATOR = register("dragon_incubator", ExtremeMonstersModBlocks.DRAGON_INCUBATOR, DragonIncubatorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> WITHER_ENERGY_CUBE = register("wither_energy_cube", ExtremeMonstersModBlocks.WITHER_ENERGY_CUBE, WitherEnergyCubeBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> COMBUSTION_GENERATOR_MK_4 = register("combustion_generator_mk_4", ExtremeMonstersModBlocks.COMBUSTION_GENERATOR_MK_4, CombustionGeneratorMk4BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MATTER_FUSION_REACTOR_4 = register("matter_fusion_reactor_4", ExtremeMonstersModBlocks.MATTER_FUSION_REACTOR_4, MatterFusionReactor4BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> WITHER_MATTER_SOLAR_PANEL = register("wither_matter_solar_panel", ExtremeMonstersModBlocks.WITHER_MATTER_SOLAR_PANEL, WitherMatterSolarPanelBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> WITHER_MATTER_RELAY = register("wither_matter_relay", ExtremeMonstersModBlocks.WITHER_MATTER_RELAY, WitherMatterRelayBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> COMBUSTION_GENERATOR_MK_5 = register("combustion_generator_mk_5", ExtremeMonstersModBlocks.COMBUSTION_GENERATOR_MK_5, CombustionGeneratorMk5BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MATTER_FUSION_REACTOR_5 = register("matter_fusion_reactor_5", ExtremeMonstersModBlocks.MATTER_FUSION_REACTOR_5, MatterFusionReactor5BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> WIRELESS_AUTO_MENDER = register("wireless_auto_mender", ExtremeMonstersModBlocks.WIRELESS_AUTO_MENDER, WirelessAutoMenderBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> TRACKER_DEFENDER_MK_5 = register("tracker_defender_mk_5", ExtremeMonstersModBlocks.TRACKER_DEFENDER_MK_5, TrackerDefenderMk5BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> ALLOY_SMELTER = register("alloy_smelter", ExtremeMonstersModBlocks.ALLOY_SMELTER, AlloySmelterBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> QUANTUM_INFUSER = register("quantum_infuser", ExtremeMonstersModBlocks.QUANTUM_INFUSER, QuantumInfuserBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> PERFECT_MATTER_FOUNDATION = register("perfect_matter_foundation", ExtremeMonstersModBlocks.PERFECT_MATTER_FOUNDATION, PerfectMatterFoundationBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> INFINITY_MATRIX = register("infinity_matrix", ExtremeMonstersModBlocks.INFINITY_MATRIX, InfinityMatrixBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> INFINITY_SIMULATION_CHAMBER = register("infinity_simulation_chamber", ExtremeMonstersModBlocks.INFINITY_SIMULATION_CHAMBER, InfinitySimulationChamberBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> WITHER_INCUBATOR = register("wither_incubator", ExtremeMonstersModBlocks.WITHER_INCUBATOR, WitherIncubatorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DARK_MATTER_GENERATOR_MK_4 = register("dark_matter_generator_mk_4", ExtremeMonstersModBlocks.DARK_MATTER_GENERATOR_MK_4, DarkMatterGeneratorMk4BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> INFINITE_WATER_SOURCE = register("infinite_water_source", ExtremeMonstersModBlocks.INFINITE_WATER_SOURCE, InfiniteWaterSourceBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> INFINITE_LAVA_SOURCE = register("infinite_lava_source", ExtremeMonstersModBlocks.INFINITE_LAVA_SOURCE, InfiniteLavaSourceBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DARK_MATTER_GENERATOR_MK_5 = register("dark_matter_generator_mk_5", ExtremeMonstersModBlocks.DARK_MATTER_GENERATOR_MK_5, DarkMatterGeneratorMk5BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> COPPER_GENERATOR = register("copper_generator", ExtremeMonstersModBlocks.COPPER_GENERATOR, CopperGeneratorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> APPLE_CULTIVATOR_MK_1 = register("apple_cultivator_mk_1", ExtremeMonstersModBlocks.APPLE_CULTIVATOR_MK_1, AppleCultivatorMk1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> APPLE_CULTIVATOR_MK_2 = register("apple_cultivator_mk_2", ExtremeMonstersModBlocks.APPLE_CULTIVATOR_MK_2, AppleCultivatorMk2BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MATTER_CATALYST_COMPRESSOR_1 = register("matter_catalyst_compressor_1", ExtremeMonstersModBlocks.MATTER_CATALYST_COMPRESSOR_1, MatterCatalystCompressor1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MATTER_CATALYST_COMPRESSOR_2 = register("matter_catalyst_compressor_2", ExtremeMonstersModBlocks.MATTER_CATALYST_COMPRESSOR_2, MatterCatalystCompressor2BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MATTER_CATALYST_COMPRESSOR_3 = register("matter_catalyst_compressor_3", ExtremeMonstersModBlocks.MATTER_CATALYST_COMPRESSOR_3, MatterCatalystCompressor3BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> IRON_GENERATOR = register("iron_generator", ExtremeMonstersModBlocks.IRON_GENERATOR, IronGeneratorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> REDSTONE_GENERATOR = register("redstone_generator", ExtremeMonstersModBlocks.REDSTONE_GENERATOR, RedstoneGeneratorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> ZIO_INSERTER = register("zio_inserter", ExtremeMonstersModBlocks.ZIO_INSERTER, ZioInserterBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> ZIO_EXPORTER = register("zio_exporter", ExtremeMonstersModBlocks.ZIO_EXPORTER, ZioExporterBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DARK_MATTER_QUANTUM_VAULT = register("dark_matter_quantum_vault", ExtremeMonstersModBlocks.DARK_MATTER_QUANTUM_VAULT, DarkMatterQuantumVaultBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> INFINITE_COBBLESTONE_SOURCE = register("infinite_cobblestone_source", ExtremeMonstersModBlocks.INFINITE_COBBLESTONE_SOURCE, InfiniteCobblestoneSourceBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> FICTIONAL_PLANET = register("fictional_planet", ExtremeMonstersModBlocks.FICTIONAL_PLANET, FictionalPlanetTileEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> INFERNO_ENERGY_ACCEPTOR = register("inferno_energy_acceptor", ExtremeMonstersModBlocks.INFERNO_ENERGY_ACCEPTOR, InfernoEnergyAcceptorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> INFERNO_MINING_CONTROLLER = register("inferno_mining_controller", ExtremeMonstersModBlocks.INFERNO_MINING_CONTROLLER, InfernoMiningControllerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> INFERNO_ITEM_OUTPUT_BLOCK = register("inferno_item_output_block", ExtremeMonstersModBlocks.INFERNO_ITEM_OUTPUT_BLOCK, InfernoItemOutputBlockBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> INFERNO_FICTIONAL_PLANET_MODEL_MODIFIER = register("inferno_fictional_planet_model_modifier", ExtremeMonstersModBlocks.INFERNO_FICTIONAL_PLANET_MODEL_MODIFIER,
			InfernoFictionalPlanetModelModifierBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> ARTIFICIAL_SUN = register("artificial_sun", ExtremeMonstersModBlocks.ARTIFICIAL_SUN, ArtificialSunTileEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> PLANETARY_REGULATOR = register("planetary_regulator", ExtremeMonstersModBlocks.PLANETARY_REGULATOR, PlanetaryRegulatorTileEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DRAGON_MINING_CONTROLLER = register("dragon_mining_controller", ExtremeMonstersModBlocks.DRAGON_MINING_CONTROLLER, DragonMiningControllerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DRAGON_ENERGY_ACCEPTOR = register("dragon_energy_acceptor", ExtremeMonstersModBlocks.DRAGON_ENERGY_ACCEPTOR, DragonEnergyAcceptorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DRAGON_ITEM_OUTPUT_BLOCK = register("dragon_item_output_block", ExtremeMonstersModBlocks.DRAGON_ITEM_OUTPUT_BLOCK, DragonItemOutputBlockBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> QUANTUM_ANCHOR = register("quantum_anchor", ExtremeMonstersModBlocks.QUANTUM_ANCHOR, QuantumAnchorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DARK_FLUID_INPUT_BLOCK = register("dark_fluid_input_block", ExtremeMonstersModBlocks.DARK_FLUID_INPUT_BLOCK, DarkFluidInputBlockBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DARK_ITEM_OUTPUT_BLOCK = register("dark_item_output_block", ExtremeMonstersModBlocks.DARK_ITEM_OUTPUT_BLOCK, DarkItemOutputBlockBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MATTER_CATALYST_BOILER_CONTROLLER = register("matter_catalyst_boiler_controller", ExtremeMonstersModBlocks.MATTER_CATALYST_BOILER_CONTROLLER,
			MatterCatalystBoilerControllerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DARK_MATTER_GROWTH_ACCELERATOR = register("dark_matter_growth_accelerator", ExtremeMonstersModBlocks.DARK_MATTER_GROWTH_ACCELERATOR,
			DarkMatterGrowthAcceleratorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> INFINITY_TRACKER_DEFENDER = register("infinity_tracker_defender", ExtremeMonstersModBlocks.INFINITY_TRACKER_DEFENDER, InfinityTrackerDefenderBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> SUPER_SMELTING_BLOCK = register("super_smelting_block", ExtremeMonstersModBlocks.SUPER_SMELTING_BLOCK, SuperSmeltingBlockBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DRAGON_QSS_CONTROLLER = register("dragon_qss_controller", ExtremeMonstersModBlocks.DRAGON_QSS_CONTROLLER, DragonQssControllerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DRAGON_QSS_OUTPUT_BLOCK = register("dragon_qss_output_block", ExtremeMonstersModBlocks.DRAGON_QSS_OUTPUT_BLOCK, DragonQssOutputBlockBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> TEAR_EXTRACTOR_MK_1 = register("tear_extractor_mk_1", ExtremeMonstersModBlocks.TEAR_EXTRACTOR_MK_1, TearExtractorMk1BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> INFERNO_MATTER_ASSEMBLER = register("inferno_matter_assembler", ExtremeMonstersModBlocks.INFERNO_MATTER_ASSEMBLER, InfernoMatterAssemblerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> TUNGSTEN_FURNACE = register("tungsten_furnace", ExtremeMonstersModBlocks.TUNGSTEN_FURNACE, TungstenFurnaceBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DUPLICATOR_MK_2 = register("duplicator_mk_2", ExtremeMonstersModBlocks.DUPLICATOR_MK_2, DuplicatorMk2BlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> TRACKER_INCUBATOR = register("tracker_incubator", ExtremeMonstersModBlocks.TRACKER_INCUBATOR, TrackerIncubatorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CONTAINED_SUPER_TRACKER = register("contained_super_tracker", ExtremeMonstersModBlocks.CONTAINED_SUPER_TRACKER, ContainedSuperTrackerTileEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> TRACKER_CONTAINMENT_CAGE = register("tracker_containment_cage", ExtremeMonstersModBlocks.TRACKER_CONTAINMENT_CAGE, TrackerContainmentCageTileEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> ARTIFICIAL_NEUTRON_STAR = register("artificial_neutron_star", ExtremeMonstersModBlocks.ARTIFICIAL_NEUTRON_STAR, ArtificialNeutronStarTileEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> SOLAR_RESIDUUM_COLLECTOR = register("solar_residuum_collector", ExtremeMonstersModBlocks.SOLAR_RESIDUUM_COLLECTOR, SolarResiduumCollectorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> HFE_UP_SCALER = register("hfe_up_scaler", ExtremeMonstersModBlocks.HFE_UP_SCALER, HFEUpScalerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> WITHER_HFE_CUBE = register("wither_hfe_cube", ExtremeMonstersModBlocks.WITHER_HFE_CUBE, WitherHfeCubeBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> HFE_DOWN_SCALER = register("hfe_down_scaler", ExtremeMonstersModBlocks.HFE_DOWN_SCALER, HfeDownScalerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> CREATIVE_HFE_GENERATOR = register("creative_hfe_generator", ExtremeMonstersModBlocks.CREATIVE_HFE_GENERATOR, CreativeHFEGeneratorBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> WITHER_MATTER_HFE_RELAY = register("wither_matter_hfe_relay", ExtremeMonstersModBlocks.WITHER_MATTER_HFE_RELAY, WitherMatterHFERelayBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> DYSON_RING_CONTROLLER = register("dyson_ring_controller", ExtremeMonstersModBlocks.DYSON_RING_CONTROLLER, DysonRingControllerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> QUANTUM_IGNITER = register("quantum_igniter", ExtremeMonstersModBlocks.QUANTUM_IGNITER, QuantumIgniterBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> PERFECT_HFE_CUBE = register("perfect_hfe_cube", ExtremeMonstersModBlocks.PERFECT_HFE_CUBE, PerfectHFECubeBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MOLECULAR_ASSEMBLER = register("molecular_assembler", ExtremeMonstersModBlocks.MOLECULAR_ASSEMBLER, MolecularAssemblerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MOLECULAR_DISSOLVER = register("molecular_dissolver", ExtremeMonstersModBlocks.MOLECULAR_DISSOLVER, MolecularDissolverBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MOLECULAR_MATTER_RESYNTHESIZER = register("molecular_matter_resynthesizer", ExtremeMonstersModBlocks.MOLECULAR_MATTER_RESYNTHESIZER,
			MolecularMatterResynthesizerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MOLECULAR_ALLOYING_FORGE = register("molecular_alloying_forge", ExtremeMonstersModBlocks.MOLECULAR_ALLOYING_FORGE, MolecularAlloyingForgeBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MOLECULAR_COMPRESSION_STATION = register("molecular_compression_station", ExtremeMonstersModBlocks.MOLECULAR_COMPRESSION_STATION,
			MolecularCompressionStationBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MICROVERSE_SIMULATOR_CONTROLLER = register("microverse_simulator_controller", ExtremeMonstersModBlocks.MICROVERSE_SIMULATOR_CONTROLLER,
			MicroverseSimulatorControllerBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MICROVERSE_ITEM_OUTPUT_BLOCK = register("microverse_item_output_block", ExtremeMonstersModBlocks.MICROVERSE_ITEM_OUTPUT_BLOCK, MicroverseItemOutputBlockBlockEntity::new);
	public static final DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> MICROVERSE_INPUT_BLOCK = register("microverse_input_block", ExtremeMonstersModBlocks.MICROVERSE_INPUT_BLOCK, MicroverseInputBlockBlockEntity::new);

	// Start of user code block custom block entities
	// End of user code block custom block entities
	private static DeferredHolder<BlockEntityType<?>, BlockEntityType<?>> register(String registryname, DeferredHolder<Block, Block> block, BlockEntityType.BlockEntitySupplier<?> supplier) {
		return REGISTRY.register(registryname, () -> BlockEntityType.Builder.of(supplier, block.get()).build(null));
	}

	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DARK_MATTER_GENERATOR.get(), (blockEntity, side) -> ((DarkMatterGeneratorBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, DARK_MATTER_GENERATOR.get(), (blockEntity, side) -> ((DarkMatterGeneratorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, BLACK_HOLE_MATTER_SOLAR_PLANEL.get(), (blockEntity, side) -> ((BlackHoleMatterSolarPlanelBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, BLACK_HOLE_MATTER_SOLAR_PLANEL.get(), (blockEntity, side) -> ((BlackHoleMatterSolarPlanelBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, NETHERITE_FUSION_REACTOR.get(), (blockEntity, side) -> ((NetheriteFusionReactorBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, NETHERITE_FUSION_REACTOR.get(), (blockEntity, side) -> ((NetheriteFusionReactorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SOUL_INSERT_MACHINE.get(), (blockEntity, side) -> ((SoulInsertMachineBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, SOUL_INSERT_MACHINE.get(), (blockEntity, side) -> ((SoulInsertMachineBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SIMULATION_CHAMBER.get(), (blockEntity, side) -> ((SimulationChamberBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, SIMULATION_CHAMBER.get(), (blockEntity, side) -> ((SimulationChamberBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, BLACK_HOLE_MATTER_ASSEMBLER.get(), (blockEntity, side) -> ((BlackHoleMatterAssemblerBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, BLACK_HOLE_MATTER_ASSEMBLER.get(), (blockEntity, side) -> ((BlackHoleMatterAssemblerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MOB_SEDUCE.get(), (blockEntity, side) -> ((MobSeduceBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, MOB_SEDUCE.get(), (blockEntity, side) -> ((MobSeduceBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CREATIVE_GENERATOR.get(), (blockEntity, side) -> ((CreativeGeneratorBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, CREATIVE_GENERATOR.get(), (blockEntity, side) -> ((CreativeGeneratorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TRACKER_DEFENDER.get(), (blockEntity, side) -> ((TrackerDefenderBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, TRACKER_DEFENDER.get(), (blockEntity, side) -> ((TrackerDefenderBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, BLACK_HOLE_MATTER_RELAY.get(), (blockEntity, side) -> ((BlackHoleMatterRelayBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, BLACK_HOLE_MATTER_RELAY.get(), (blockEntity, side) -> ((BlackHoleMatterRelayBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MATTER_FUSION_REACTOR_1.get(), (blockEntity, side) -> ((MatterFusionReactor1BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, MATTER_FUSION_REACTOR_1.get(), (blockEntity, side) -> ((MatterFusionReactor1BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MATTER_CATALYST_MAKER.get(), (blockEntity, side) -> ((MatterCatalystMakerBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, MATTER_CATALYST_MAKER.get(), (blockEntity, side) -> ((MatterCatalystMakerBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TRACKER_DEFENDER_MK_2.get(), (blockEntity, side) -> ((TrackerDefenderMk2BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, TRACKER_DEFENDER_MK_2.get(), (blockEntity, side) -> ((TrackerDefenderMk2BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DARK_MATTER_RELAY.get(), (blockEntity, side) -> ((DarkMatterRelayBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, DARK_MATTER_RELAY.get(), (blockEntity, side) -> ((DarkMatterRelayBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, COMBUSTION_GENERATOR.get(), (blockEntity, side) -> ((CombustionGeneratorBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, COMBUSTION_GENERATOR.get(), (blockEntity, side) -> ((CombustionGeneratorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DARK_MATTER_SOLAR_PANEL.get(), (blockEntity, side) -> ((DarkMatterSolarPanelBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, DARK_MATTER_SOLAR_PANEL.get(), (blockEntity, side) -> ((DarkMatterSolarPanelBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SPIDER_EGG.get(), (blockEntity, side) -> ((SpiderEggBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, COMBUSTION_GENERATOR_MK_2.get(), (blockEntity, side) -> ((CombustionGeneratorMk2BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, COMBUSTION_GENERATOR_MK_2.get(), (blockEntity, side) -> ((CombustionGeneratorMk2BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MATTER_FUSION_REACTOR_2.get(), (blockEntity, side) -> ((MatterFusionReactor2BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DUPLICATOR.get(), (blockEntity, side) -> ((DuplicatorBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, DUPLICATOR.get(), (blockEntity, side) -> ((DuplicatorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MOB_ATTACKER.get(), (blockEntity, side) -> ((MobAttackerBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, MOB_ATTACKER.get(), (blockEntity, side) -> ((MobAttackerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, PROJECTILE_REMOVER.get(), (blockEntity, side) -> ((ProjectileRemoverBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, PROJECTILE_REMOVER.get(), (blockEntity, side) -> ((ProjectileRemoverBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DARK_MATTER_ASSEMBLER.get(), (blockEntity, side) -> ((DarkMatterAssemblerBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, DARK_MATTER_ASSEMBLER.get(), (blockEntity, side) -> ((DarkMatterAssemblerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DIAMOND_GENERATOR.get(), (blockEntity, side) -> ((DiamondGeneratorBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, DIAMOND_GENERATOR.get(), (blockEntity, side) -> ((DiamondGeneratorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SUPER_MAGMA.get(), (blockEntity, side) -> ((SuperMagmaBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TRACKER_DEFENDER_MK_3.get(), (blockEntity, side) -> ((TrackerDefenderMk3BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, TRACKER_DEFENDER_MK_3.get(), (blockEntity, side) -> ((TrackerDefenderMk3BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, INFERNO_MATTER_SOLAR_PANEL.get(), (blockEntity, side) -> ((InfernoMatterSolarPanelBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, INFERNO_MATTER_SOLAR_PANEL.get(), (blockEntity, side) -> ((InfernoMatterSolarPanelBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, INFERNO_MATTER_RELAY.get(), (blockEntity, side) -> ((InfernoMatterRelayBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, INFERNO_MATTER_RELAY.get(), (blockEntity, side) -> ((InfernoMatterRelayBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, COMBUSTION_GENERATOR_MK_3.get(), (blockEntity, side) -> ((CombustionGeneratorMk3BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, COMBUSTION_GENERATOR_MK_3.get(), (blockEntity, side) -> ((CombustionGeneratorMk3BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MATTER_FUSION_REACTOR_3.get(), (blockEntity, side) -> ((MatterFusionReactor3BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, MATTER_FUSION_REACTOR_3.get(), (blockEntity, side) -> ((MatterFusionReactor3BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SOUL_INSERT_MACHINE_MK_2.get(), (blockEntity, side) -> ((SoulInsertMachineMk2BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, SOUL_INSERT_MACHINE_MK_2.get(), (blockEntity, side) -> ((SoulInsertMachineMk2BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SIMULATION_CHAMBER_MK_2.get(), (blockEntity, side) -> ((SimulationChamberMk2BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, SIMULATION_CHAMBER_MK_2.get(), (blockEntity, side) -> ((SimulationChamberMk2BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SOUL_INSERT_MACHINE_MK_3.get(), (blockEntity, side) -> ((SoulInsertMachineMk3BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, SOUL_INSERT_MACHINE_MK_3.get(), (blockEntity, side) -> ((SoulInsertMachineMk3BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SIMULATION_CHAMBER_MK_3.get(), (blockEntity, side) -> ((SimulationChamberMK3BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, SIMULATION_CHAMBER_MK_3.get(), (blockEntity, side) -> ((SimulationChamberMK3BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DARK_MATTER_GENERATOR_MK_2.get(), (blockEntity, side) -> ((DarkMatterGeneratorMk2BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, DARK_MATTER_GENERATOR_MK_2.get(), (blockEntity, side) -> ((DarkMatterGeneratorMk2BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DARK_MATTER_GENERATOR_MK_3.get(), (blockEntity, side) -> ((DarkMatterGeneratorMk3BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, DARK_MATTER_GENERATOR_MK_3.get(), (blockEntity, side) -> ((DarkMatterGeneratorMk3BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, FORCE_EMITTER.get(), (blockEntity, side) -> ((ForceEmitterBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, FORCE_EMITTER.get(), (blockEntity, side) -> ((ForceEmitterBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DRAGON_MATTER_SOLAR_PANEL.get(), (blockEntity, side) -> ((DragonMatterSolarPanelBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, DRAGON_MATTER_SOLAR_PANEL.get(), (blockEntity, side) -> ((DragonMatterSolarPanelBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TRACKER_DEFENDER_MK_4.get(), (blockEntity, side) -> ((TrackerDefenderMk4BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, TRACKER_DEFENDER_MK_4.get(), (blockEntity, side) -> ((TrackerDefenderMk4BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, OMEGA_D_CORE_STABILIZER.get(), (blockEntity, side) -> ((OmegaDCoreStabilizerBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, OMEGA_D_CORE_STABILIZER.get(), (blockEntity, side) -> ((OmegaDCoreStabilizerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, OMEGA_D_CORE.get(), (blockEntity, side) -> ((OmegaDCoreBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DRAGON_MATTER_RELAY.get(), (blockEntity, side) -> ((DragonMatterRelayBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, DRAGON_MATTER_RELAY.get(), (blockEntity, side) -> ((DragonMatterRelayBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, INFERNO_ENERGY_CUBE.get(), (blockEntity, side) -> ((InfernoEnergyCubeBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, INFERNO_ENERGY_CUBE.get(), (blockEntity, side) -> ((InfernoEnergyCubeBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DRAGON_ENERGY_CUBE.get(), (blockEntity, side) -> ((DragonEnergyCubeBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, DRAGON_ENERGY_CUBE.get(), (blockEntity, side) -> ((DragonEnergyCubeBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, ICE_MAKER.get(), (blockEntity, side) -> ((IceMakerBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, ICE_MAKER.get(), (blockEntity, side) -> ((IceMakerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, ICE_MAKER.get(), (blockEntity, side) -> ((IceMakerBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DRAGON_INCUBATOR.get(), (blockEntity, side) -> ((DragonIncubatorBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, DRAGON_INCUBATOR.get(), (blockEntity, side) -> ((DragonIncubatorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, WITHER_ENERGY_CUBE.get(), (blockEntity, side) -> ((WitherEnergyCubeBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, WITHER_ENERGY_CUBE.get(), (blockEntity, side) -> ((WitherEnergyCubeBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, COMBUSTION_GENERATOR_MK_4.get(), (blockEntity, side) -> ((CombustionGeneratorMk4BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, COMBUSTION_GENERATOR_MK_4.get(), (blockEntity, side) -> ((CombustionGeneratorMk4BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MATTER_FUSION_REACTOR_4.get(), (blockEntity, side) -> ((MatterFusionReactor4BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, MATTER_FUSION_REACTOR_4.get(), (blockEntity, side) -> ((MatterFusionReactor4BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, WITHER_MATTER_SOLAR_PANEL.get(), (blockEntity, side) -> ((WitherMatterSolarPanelBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, WITHER_MATTER_SOLAR_PANEL.get(), (blockEntity, side) -> ((WitherMatterSolarPanelBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, WITHER_MATTER_RELAY.get(), (blockEntity, side) -> ((WitherMatterRelayBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, WITHER_MATTER_RELAY.get(), (blockEntity, side) -> ((WitherMatterRelayBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, COMBUSTION_GENERATOR_MK_5.get(), (blockEntity, side) -> ((CombustionGeneratorMk5BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, COMBUSTION_GENERATOR_MK_5.get(), (blockEntity, side) -> ((CombustionGeneratorMk5BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MATTER_FUSION_REACTOR_5.get(), (blockEntity, side) -> ((MatterFusionReactor5BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, MATTER_FUSION_REACTOR_5.get(), (blockEntity, side) -> ((MatterFusionReactor5BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, WIRELESS_AUTO_MENDER.get(), (blockEntity, side) -> ((WirelessAutoMenderBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, WIRELESS_AUTO_MENDER.get(), (blockEntity, side) -> ((WirelessAutoMenderBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TRACKER_DEFENDER_MK_5.get(), (blockEntity, side) -> ((TrackerDefenderMk5BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, TRACKER_DEFENDER_MK_5.get(), (blockEntity, side) -> ((TrackerDefenderMk5BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, ALLOY_SMELTER.get(), (blockEntity, side) -> ((AlloySmelterBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, ALLOY_SMELTER.get(), (blockEntity, side) -> ((AlloySmelterBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, ALLOY_SMELTER.get(), (blockEntity, side) -> ((AlloySmelterBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, QUANTUM_INFUSER.get(), (blockEntity, side) -> ((QuantumInfuserBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, PERFECT_MATTER_FOUNDATION.get(), (blockEntity, side) -> ((PerfectMatterFoundationBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, INFINITY_MATRIX.get(), (blockEntity, side) -> ((InfinityMatrixBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, INFINITY_MATRIX.get(), (blockEntity, side) -> ((InfinityMatrixBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, INFINITY_SIMULATION_CHAMBER.get(), (blockEntity, side) -> ((InfinitySimulationChamberBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, INFINITY_SIMULATION_CHAMBER.get(), (blockEntity, side) -> ((InfinitySimulationChamberBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, WITHER_INCUBATOR.get(), (blockEntity, side) -> ((WitherIncubatorBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, WITHER_INCUBATOR.get(), (blockEntity, side) -> ((WitherIncubatorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DARK_MATTER_GENERATOR_MK_4.get(), (blockEntity, side) -> ((DarkMatterGeneratorMk4BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, DARK_MATTER_GENERATOR_MK_4.get(), (blockEntity, side) -> ((DarkMatterGeneratorMk4BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, INFINITE_WATER_SOURCE.get(), (blockEntity, side) -> ((InfiniteWaterSourceBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, INFINITE_WATER_SOURCE.get(), (blockEntity, side) -> ((InfiniteWaterSourceBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, INFINITE_LAVA_SOURCE.get(), (blockEntity, side) -> ((InfiniteLavaSourceBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, INFINITE_LAVA_SOURCE.get(), (blockEntity, side) -> ((InfiniteLavaSourceBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DARK_MATTER_GENERATOR_MK_5.get(), (blockEntity, side) -> ((DarkMatterGeneratorMk5BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, DARK_MATTER_GENERATOR_MK_5.get(), (blockEntity, side) -> ((DarkMatterGeneratorMk5BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, COPPER_GENERATOR.get(), (blockEntity, side) -> ((CopperGeneratorBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, COPPER_GENERATOR.get(), (blockEntity, side) -> ((CopperGeneratorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, APPLE_CULTIVATOR_MK_1.get(), (blockEntity, side) -> ((AppleCultivatorMk1BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, APPLE_CULTIVATOR_MK_1.get(), (blockEntity, side) -> ((AppleCultivatorMk1BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, APPLE_CULTIVATOR_MK_2.get(), (blockEntity, side) -> ((AppleCultivatorMk2BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, APPLE_CULTIVATOR_MK_2.get(), (blockEntity, side) -> ((AppleCultivatorMk2BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MATTER_CATALYST_COMPRESSOR_1.get(), (blockEntity, side) -> ((MatterCatalystCompressor1BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, MATTER_CATALYST_COMPRESSOR_1.get(), (blockEntity, side) -> ((MatterCatalystCompressor1BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MATTER_CATALYST_COMPRESSOR_2.get(), (blockEntity, side) -> ((MatterCatalystCompressor2BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, MATTER_CATALYST_COMPRESSOR_2.get(), (blockEntity, side) -> ((MatterCatalystCompressor2BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MATTER_CATALYST_COMPRESSOR_3.get(), (blockEntity, side) -> ((MatterCatalystCompressor3BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, MATTER_CATALYST_COMPRESSOR_3.get(), (blockEntity, side) -> ((MatterCatalystCompressor3BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, IRON_GENERATOR.get(), (blockEntity, side) -> ((IronGeneratorBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, IRON_GENERATOR.get(), (blockEntity, side) -> ((IronGeneratorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, REDSTONE_GENERATOR.get(), (blockEntity, side) -> ((RedstoneGeneratorBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, REDSTONE_GENERATOR.get(), (blockEntity, side) -> ((RedstoneGeneratorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, ZIO_INSERTER.get(), (blockEntity, side) -> ((ZioInserterBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, ZIO_EXPORTER.get(), (blockEntity, side) -> ((ZioExporterBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DARK_MATTER_QUANTUM_VAULT.get(), (blockEntity, side) -> ((DarkMatterQuantumVaultBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, INFINITE_COBBLESTONE_SOURCE.get(), (blockEntity, side) -> ((InfiniteCobblestoneSourceBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, INFERNO_ENERGY_ACCEPTOR.get(), (blockEntity, side) -> ((InfernoEnergyAcceptorBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, INFERNO_ENERGY_ACCEPTOR.get(), (blockEntity, side) -> ((InfernoEnergyAcceptorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, INFERNO_MINING_CONTROLLER.get(), (blockEntity, side) -> ((InfernoMiningControllerBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, INFERNO_ITEM_OUTPUT_BLOCK.get(), (blockEntity, side) -> ((InfernoItemOutputBlockBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, INFERNO_FICTIONAL_PLANET_MODEL_MODIFIER.get(), (blockEntity, side) -> ((InfernoFictionalPlanetModelModifierBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DRAGON_MINING_CONTROLLER.get(), (blockEntity, side) -> ((DragonMiningControllerBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DRAGON_ENERGY_ACCEPTOR.get(), (blockEntity, side) -> ((DragonEnergyAcceptorBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, DRAGON_ENERGY_ACCEPTOR.get(), (blockEntity, side) -> ((DragonEnergyAcceptorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DRAGON_ITEM_OUTPUT_BLOCK.get(), (blockEntity, side) -> ((DragonItemOutputBlockBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, QUANTUM_ANCHOR.get(), (blockEntity, side) -> ((QuantumAnchorBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DARK_FLUID_INPUT_BLOCK.get(), (blockEntity, side) -> ((DarkFluidInputBlockBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, DARK_FLUID_INPUT_BLOCK.get(), (blockEntity, side) -> ((DarkFluidInputBlockBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DARK_ITEM_OUTPUT_BLOCK.get(), (blockEntity, side) -> ((DarkItemOutputBlockBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MATTER_CATALYST_BOILER_CONTROLLER.get(), (blockEntity, side) -> ((MatterCatalystBoilerControllerBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DARK_MATTER_GROWTH_ACCELERATOR.get(), (blockEntity, side) -> ((DarkMatterGrowthAcceleratorBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, DARK_MATTER_GROWTH_ACCELERATOR.get(), (blockEntity, side) -> ((DarkMatterGrowthAcceleratorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, INFINITY_TRACKER_DEFENDER.get(), (blockEntity, side) -> ((InfinityTrackerDefenderBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, INFINITY_TRACKER_DEFENDER.get(), (blockEntity, side) -> ((InfinityTrackerDefenderBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SUPER_SMELTING_BLOCK.get(), (blockEntity, side) -> ((SuperSmeltingBlockBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DRAGON_QSS_CONTROLLER.get(), (blockEntity, side) -> ((DragonQssControllerBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, DRAGON_QSS_CONTROLLER.get(), (blockEntity, side) -> ((DragonQssControllerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DRAGON_QSS_OUTPUT_BLOCK.get(), (blockEntity, side) -> ((DragonQssOutputBlockBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TEAR_EXTRACTOR_MK_1.get(), (blockEntity, side) -> ((TearExtractorMk1BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, TEAR_EXTRACTOR_MK_1.get(), (blockEntity, side) -> ((TearExtractorMk1BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, INFERNO_MATTER_ASSEMBLER.get(), (blockEntity, side) -> ((InfernoMatterAssemblerBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, INFERNO_MATTER_ASSEMBLER.get(), (blockEntity, side) -> ((InfernoMatterAssemblerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TUNGSTEN_FURNACE.get(), (blockEntity, side) -> ((TungstenFurnaceBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, TUNGSTEN_FURNACE.get(), (blockEntity, side) -> ((TungstenFurnaceBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DUPLICATOR_MK_2.get(), (blockEntity, side) -> ((DuplicatorMk2BlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, DUPLICATOR_MK_2.get(), (blockEntity, side) -> ((DuplicatorMk2BlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, TRACKER_INCUBATOR.get(), (blockEntity, side) -> ((TrackerIncubatorBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, TRACKER_INCUBATOR.get(), (blockEntity, side) -> ((TrackerIncubatorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, SOLAR_RESIDUUM_COLLECTOR.get(), (blockEntity, side) -> ((SolarResiduumCollectorBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, SOLAR_RESIDUUM_COLLECTOR.get(), (blockEntity, side) -> ((SolarResiduumCollectorBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, HFE_UP_SCALER.get(), (blockEntity, side) -> ((HFEUpScalerBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, HFE_UP_SCALER.get(), (blockEntity, side) -> ((HFEUpScalerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, WITHER_HFE_CUBE.get(), (blockEntity, side) -> ((WitherHfeCubeBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, HFE_DOWN_SCALER.get(), (blockEntity, side) -> ((HfeDownScalerBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, HFE_DOWN_SCALER.get(), (blockEntity, side) -> ((HfeDownScalerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, CREATIVE_HFE_GENERATOR.get(), (blockEntity, side) -> ((CreativeHFEGeneratorBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, WITHER_MATTER_HFE_RELAY.get(), (blockEntity, side) -> ((WitherMatterHFERelayBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, DYSON_RING_CONTROLLER.get(), (blockEntity, side) -> ((DysonRingControllerBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, QUANTUM_IGNITER.get(), (blockEntity, side) -> ((QuantumIgniterBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, PERFECT_HFE_CUBE.get(), (blockEntity, side) -> ((PerfectHFECubeBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MOLECULAR_ASSEMBLER.get(), (blockEntity, side) -> ((MolecularAssemblerBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, MOLECULAR_ASSEMBLER.get(), (blockEntity, side) -> ((MolecularAssemblerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, MOLECULAR_ASSEMBLER.get(), (blockEntity, side) -> ((MolecularAssemblerBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MOLECULAR_DISSOLVER.get(), (blockEntity, side) -> ((MolecularDissolverBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, MOLECULAR_DISSOLVER.get(), (blockEntity, side) -> ((MolecularDissolverBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, MOLECULAR_DISSOLVER.get(), (blockEntity, side) -> ((MolecularDissolverBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MOLECULAR_MATTER_RESYNTHESIZER.get(), (blockEntity, side) -> ((MolecularMatterResynthesizerBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, MOLECULAR_MATTER_RESYNTHESIZER.get(), (blockEntity, side) -> ((MolecularMatterResynthesizerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, MOLECULAR_MATTER_RESYNTHESIZER.get(), (blockEntity, side) -> ((MolecularMatterResynthesizerBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MOLECULAR_ALLOYING_FORGE.get(), (blockEntity, side) -> ((MolecularAlloyingForgeBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, MOLECULAR_ALLOYING_FORGE.get(), (blockEntity, side) -> ((MolecularAlloyingForgeBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, MOLECULAR_ALLOYING_FORGE.get(), (blockEntity, side) -> ((MolecularAlloyingForgeBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MOLECULAR_COMPRESSION_STATION.get(), (blockEntity, side) -> ((MolecularCompressionStationBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, MOLECULAR_COMPRESSION_STATION.get(), (blockEntity, side) -> ((MolecularCompressionStationBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.FluidHandler.BLOCK, MOLECULAR_COMPRESSION_STATION.get(), (blockEntity, side) -> ((MolecularCompressionStationBlockEntity) blockEntity).getFluidTank());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MICROVERSE_SIMULATOR_CONTROLLER.get(), (blockEntity, side) -> ((MicroverseSimulatorControllerBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, MICROVERSE_SIMULATOR_CONTROLLER.get(), (blockEntity, side) -> ((MicroverseSimulatorControllerBlockEntity) blockEntity).getEnergyStorage());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MICROVERSE_ITEM_OUTPUT_BLOCK.get(), (blockEntity, side) -> ((MicroverseItemOutputBlockBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, MICROVERSE_INPUT_BLOCK.get(), (blockEntity, side) -> ((MicroverseInputBlockBlockEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.ItemHandler.BLOCK, PLANETARY_REGULATOR.get(), (blockEntity, side) -> ((PlanetaryRegulatorTileEntity) blockEntity).getItemHandler());
		event.registerBlockEntity(Capabilities.EnergyStorage.BLOCK, PLANETARY_REGULATOR.get(), (blockEntity, side) -> ((PlanetaryRegulatorTileEntity) blockEntity).getEnergyStorage());
	}
}
