modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="extreme_monsters"
version="1.6.1.4"
displayName="Extreme monsters"
displayURL="https://I.want.website.T_T"
logoFile="logo.png"
credits="Special thanks to Mcreator"
authors="killmkill97 (in curse forge: kiilmkiil97)"
description="Feel extreme in minecraft"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.extreme_monsters]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.extreme_monsters]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.extreme_monsters]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.extreme_monsters]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration