modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="extreme_monsters"
version="1.12.6.1"
displayName="Extreme monsters"
displayURL="https://www.curseforge.com/minecraft/mc-mods/extreme-monsters"
logoFile="logo.png"
credits="Special thanks to Mcreator"
authors="killmkill97 (in curse forge: kiilmkiil97)"
description="Feel extreme in minecraft"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.extreme_monsters]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.extreme_monsters]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.extreme_monsters]]
    modId="curios_api"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.extreme_monsters]]
    modId="geckolib"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.extreme_monsters]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration